
DROP TABLE APPROVAL;
DROP TABLE DRAFT;
DROP TABLE FORMBOX;
DROP TABLE MYBOX; 


DROP SEQUENCE FORMCODE_SEQ;
DROP SEQUENCE DOCNO_SEQ;
DROP SEQUENCE TEMPDOCNO_SEQ;

-- 양식함 코드 시퀀스
CREATE SEQUENCE FORMCODE_SEQ
START WITH 100
INCREMENT BY 10
NOMAXVALUE
MINVALUE 100
NOCYCLE
NOCACHE;


-- 문서번호 시퀀스
CREATE SEQUENCE DOCNO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

-- 임시보관문서번호 시퀀스
CREATE SEQUENCE TEMPDOCNO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;


-- 전자결재 양식함 테이블 
CREATE TABLE FORMBOX  (
 FORMCODE NUMBER	NOT NULL,
 FORMTYPE VARCHAR2(100)	NOT NULL,
 FORMNAME VARCHAR2(100)	NOT NULL,
 FORMCONTENT VARCHAR2(1000)	NOT NULL,

 CONSTRAINT FORMBOX_PK PRIMARY KEY (FORMCODE)
);

COMMENT ON COLUMN FORMBOX.FORMCODE IS '문서양식코드';
COMMENT ON COLUMN FORMBOX.FORMTYPE IS '문서양식분류';
COMMENT ON COLUMN FORMBOX.FORMNAME IS '문서양식명';
COMMENT ON COLUMN FORMBOX.FORMCONTENT IS '문서양식내용';

-- 전자결재 테이블 - 내문서함
CREATE TABLE MYBOX  (
 MYBOXCODE CHAR(1)	NOT NULL,
 EMPNO VARCHAR2(20)	NOT NULL,
 MYBOXNAME VARCHAR2(30)	NOT NULL,
 
 CONSTRAINT MEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE,
 CONSTRAINT MYBOX_PK PRIMARY KEY (MYBOXCODE, EMPNO)

);

COMMENT ON COLUMN MYBOX.MYBOXCODE IS '내문서함코드';
COMMENT ON COLUMN MYBOX.EMPNO IS '사번';
COMMENT ON COLUMN MYBOX.MYBOXNAME IS '내문서함명';

-- 전자결재 기안 테이블 
CREATE TABLE DRAFT  (
 DOCNO NUMBER,
 EMPNO VARCHAR2(20)	 NOT NULL,
 FORMCODE NUMBER	NOT NULL,
 DOCTITLE VARCHAR2(150)	NOT NULL,
 DOCCONTENT VARCHAR2(4000)	NOT NULL,
 ORIGINFILE VARCHAR2(100)	NULL,
 RENAMEFILE VARCHAR2(100)	NULL,
 DRAFTDATE DATE	DEFAULT SYSDATE	NOT NULL,
 PROGRESS CHAR(1)	DEFAULT 0	NOT NULL,
 DISPLAY CHAR(1) NOT NULL,
 MYBOXCODE CHAR(1)	NULL,

CONSTRAINT DRAFT_PK PRIMARY KEY (DOCNO),
CONSTRAINT DEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE,
CONSTRAINT FORMCODE_FK FOREIGN KEY (FORMCODE) REFERENCES FORMBOX ON DELETE CASCADE,
CONSTRAINT MYBOXCODE_FK FOREIGN KEY (MYBOXCODE, EMPNO) REFERENCES MYBOX ON DELETE SET NULL
);

COMMENT ON COLUMN DRAFT.DOCNO IS '문서번호';
COMMENT ON COLUMN DRAFT.EMPNO IS '사번';
COMMENT ON COLUMN DRAFT.FORMCODE IS '문서양식코드';
COMMENT ON COLUMN DRAFT.DOCTITLE IS '문서제목';
COMMENT ON COLUMN DRAFT.DOCCONTENT IS '문서내용';
COMMENT ON COLUMN DRAFT.ORIGINFILE IS '원래파일명';
COMMENT ON COLUMN DRAFT.RENAMEFILE IS '변경된파일명';
COMMENT ON COLUMN DRAFT.DRAFTDATE IS '문서작성날짜';
COMMENT ON COLUMN DRAFT.PROGRESS IS '문서진행상태';
COMMENT ON COLUMN DRAFT.DISPLAY IS '공개여부';
COMMENT ON COLUMN DRAFT.MYBOXCODE IS '내문서함코드';


-- 전자결재 테이블 - 결재완료
CREATE TABLE APPROVAL  (
 DOCNO NUMBER	NOT NULL REFERENCES DRAFT,
 EMPNO VARCHAR2(20)	NOT NULL REFERENCES EMPLOYEE,
 APPDATE DATE DEFAULT SYSDATE NOT NULL,
 FEEDBACK VARCHAR2(2000)	NULL,
 SIGNIMG VARCHAR2(100)	NOT NULL,
 
 CONSTRAINT ADOCNO_FK FOREIGN KEY (DOCNO) REFERENCES  DRAFT ON DELETE CASCADE,
 CONSTRAINT APPROVAL_PK PRIMARY KEY (DOCNO),
 CONSTRAINT AEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE 
);

COMMENT ON COLUMN APPROVAL.DOCNO IS '문서번호';
COMMENT ON COLUMN APPROVAL.EMPNO IS '사번';
COMMENT ON COLUMN APPROVAL.APPDATE IS '결재일';
COMMENT ON COLUMN APPROVAL.FEEDBACK IS '첨삭및의견';
COMMENT ON COLUMN APPROVAL.SIGNIMG IS '서명파일명';


INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 1', '일반 기안서', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 2', '휴가 신청서', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 3', '기타1', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 4', '기타2', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 5', '기타3', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 6', '기타4', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 7', '기타5', '공용');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 8', '직원 업무일지', '업무일지');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '기안서 양식 9', '관리자 업무일지', '업무일지');



INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'10001', 
'100', 
'기안1', 
'기안내용1', 
NULL, 
NULL, 
SYSDATE, 
'3', 
'Y', 
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'110', 
'기안2', 
'기안내용2', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'Y', 
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'10001', 
'100', 
'기안3', 
'기안내용3', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'Y', 
NULL);


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'50001', 
'170', 
'기안4', 
'기안내용4', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'N', 
NULL);


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'50001', 
'110', 
'기안5', 
'기안내용5', 
NULL, 
NULL, 
SYSDATE, 
'2', 
'Y', 
NULL);


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'100', 
'기안6', 
'기안내용6', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'N', 
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'70001', 
'110', 
'기안7', 
'기안내용7', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'N', 
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'10001', 
'170', 
'기안8', 
'기안내용8', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'N', 
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'170', 
'기안9', 
'기안내용9', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'N', 
NULL);


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'70001', 
'120', 
'기안10', 
'기안내용10', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'N', 
NULL);

COMMIT;