DROP TABLE MYBOX; 
DROP TABLE MYBOXLIST;
DROP TABLE BUSINESSLOG;
DROP TABLE APPLINE;
DROP TABLE LINELIST;
DROP TABLE PROCEDURE;
DROP TABLE DRAFT;
DROP TABLE FORMBOX;



DROP SEQUENCE FORMCODE_SEQ;
DROP SEQUENCE DOCNO_SEQ;
DROP SEQUENCE TEMPDOCNO_SEQ;

-- 양식함 코드 시퀀스
CREATE SEQUENCE FORMCODE_SEQ
START WITH 100
INCREMENT BY 10
NOMAXVALUE
MINVALUE 100
NOCYCLE
NOCACHE;


-- 문서번호 시퀀스
CREATE SEQUENCE DOCNO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

-- 임시보관문서번호 시퀀스
CREATE SEQUENCE TEMPDOCNO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;



-- 전자결재 양식함 테이블 
CREATE TABLE FORMBOX  (
 FORMCODE NUMBER	NOT NULL,
 FORMTYPE VARCHAR2(100)	NOT NULL,
 FORMNAME VARCHAR2(100)	NOT NULL,
 FORMCONTENT LONG NOT NULL,

 CONSTRAINT FORMBOX_PK PRIMARY KEY (FORMCODE)
);

COMMENT ON COLUMN FORMBOX.FORMCODE IS '문서양식코드';
COMMENT ON COLUMN FORMBOX.FORMTYPE IS '문서분류';
COMMENT ON COLUMN FORMBOX.FORMNAME IS '문서양식명';
COMMENT ON COLUMN FORMBOX.FORMCONTENT IS '문서양식내용';


--결재라인 목록

CREATE TABLE LINELIST  (
 LINENO NUMBER	NOT NULL,
 EMPNO VARCHAR2(20)	 NOT NULL,
 LINENAME VARCHAR2(100)	NOT NULL,
 LINECONTENT VARCHAR2(200) NOT NULL,

 CONSTRAINT LINELIST_PK PRIMARY KEY (LINENO),
 CONSTRAINT LEMONO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE
);

COMMENT ON COLUMN LINELIST.LINENO IS '결재선 코드';
COMMENT ON COLUMN LINELIST.EMPNO IS '사번';
COMMENT ON COLUMN LINELIST.LINENAME IS '결재선 이름';
COMMENT ON COLUMN LINELIST.LINENAME IS '결재선 내용';

CREATE TABLE APPLINE  (
 LINENO NUMBER	NOT NULL,
 EMPNO VARCHAR2(20)	 NOT NULL,
 SIGNSTEP CHAR(1) NOT NULL,

 CONSTRAINT AEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE,
 CONSTRAINT APPLINE_FK FOREIGN KEY (LINENO) REFERENCES LINELIST,
 CONSTRAINT ALINESTEP_PK PRIMARY KEY (LINENO, SIGNSTEP)
);

COMMENT ON COLUMN APPLINE.LINENO IS '결재선 코드';
COMMENT ON COLUMN APPLINE.EMPNO IS '사번';
COMMENT ON COLUMN APPLINE.SIGNSTEP IS '결재순서';



-- 전자결재 기안 테이블 
CREATE TABLE DRAFT  (
 DOCNO NUMBER,
 EMPNO VARCHAR2(20)	 NOT NULL,
 FORMCODE NUMBER	NOT NULL,
 DOCTITLE VARCHAR2(150)	NOT NULL,
 DOCCONTENT LONG	NOT NULL,
 ORIGINFILE VARCHAR2(100)	NULL,
 RENAMEFILE VARCHAR2(100)	NULL,
 DRAFTDATE DATE	DEFAULT SYSDATE	NOT NULL,
 DOCSTATUS CHAR(1)	DEFAULT 0	NOT NULL, -- 현재 문서 상태... 0 : 대기중, 1 : 진행중, 2 : 완료, 3 : 중지, 4 : 임시저장
 APPROVER VARCHAR2(1000) NULL, -- 결재자 경로 지정... 최대 5명까지 지정
 FEEDBACK VARCHAR2(2000)	NULL,
 DEADLINE DATE NOT NULL,
 LINENO NUMBER NULL,
 DISPLAY VARCHAR(1000) NULL, --공람자 지정... 최대 5명까지 지정 --> 없으면 none  
 
 CONSTRAINT DRAFT_PK PRIMARY KEY (DOCNO),
 CONSTRAINT DEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE SET NULL,
 CONSTRAINT FORMCODE_FK FOREIGN KEY (FORMCODE) REFERENCES FORMBOX ON DELETE SET NULL,
 CONSTRAINT DLINENO_FK FOREIGN KEY (LINENO) REFERENCES DRAFT ON DELETE SET NULL
);

COMMENT ON COLUMN DRAFT.DOCNO IS '문서번호';
COMMENT ON COLUMN DRAFT.EMPNO IS '기안자';
COMMENT ON COLUMN DRAFT.FORMCODE IS '문서양식코드';
COMMENT ON COLUMN DRAFT.DOCTITLE IS '문서제목';
COMMENT ON COLUMN DRAFT.DOCCONTENT IS '문서내용';
COMMENT ON COLUMN DRAFT.ORIGINFILE IS '원래파일명';
COMMENT ON COLUMN DRAFT.RENAMEFILE IS '변경된파일명';
COMMENT ON COLUMN DRAFT.DRAFTDATE IS '문서작성날짜';
COMMENT ON COLUMN DRAFT.DOCSTATUS IS '문서진행상태';
COMMENT ON COLUMN DRAFT.APPROVER IS '결재자경로';
COMMENT ON COLUMN DRAFT.FEEDBACK IS '첨삭및의견';
COMMENT ON COLUMN DRAFT.DEADLINE IS '결재기한';
COMMENT ON COLUMN DRAFT.LINENO IS '결재선코드';
COMMENT ON COLUMN DRAFT.DISPLAY IS '공람자지정';


CREATE TABLE PROCEDURE (
 DOCNO NUMBER NOT NULL,
 APPNO VARCHAR2(20) NULL,  -- 결재자번호
 APPSTEP CHAR(1) NOT NULL, -- 결재 단계 : 1~5명의 결재자 순서별 진행
 SIGNRESULT CHAR(1) NULL, -- 현재까지의 결재 결과 1 : 승인, 2 : 반려, 3 : 보류 
 APPDATE DATE DEFAULT SYSDATE NULL, -- 결재날짜 --> 받은날짜는?
 LINENO NUMBER NULL,

 CONSTRAINT PDOCNO_FK FOREIGN KEY (DOCNO) REFERENCES DRAFT ON DELETE CASCADE,
 CONSTRAINT PLINENO_FK FOREIGN KEY (LINENO) REFERENCES DRAFT ON DELETE SET NULL
);

COMMENT ON COLUMN PROCEDURE.DOCNO IS '문서번호';
COMMENT ON COLUMN PROCEDURE.APPNO IS '결재자번호';
COMMENT ON COLUMN PROCEDURE.APPSTEP IS '결재단계';
COMMENT ON COLUMN PROCEDURE.SIGNRESULT IS '결재결과';
COMMENT ON COLUMN PROCEDURE.APPDATE IS '결재완료날짜';
COMMENT ON COLUMN PROCEDURE.LINENO IS '결재선코드';


-- 전자결재 테이블 - 내문서함
CREATE TABLE MYBOXLIST  (
 MYBOXCODE CHAR(1)	NOT NULL,
 EMPNO VARCHAR2(20)	 NOT NULL,
 MYBOXNAME VARCHAR2(30)	NOT NULL,
 
 CONSTRAINT MEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE,
 CONSTRAINT MYBOX_PK PRIMARY KEY (MYBOXCODE, EMPNO)

);

COMMENT ON COLUMN MYBOXLIST.MYBOXCODE IS '내문서함코드';
COMMENT ON COLUMN MYBOXLIST.EMPNO IS '사번';
COMMENT ON COLUMN MYBOXLIST.MYBOXNAME IS '내문서함명';

-- 전자결재 테이블 - 내문서함 목록
CREATE TABLE MYBOX  (
 MYBOXCODE CHAR(1)	NOT NULL,
 EMPNO VARCHAR2(20)	 NOT NULL,
 DOCNO NUMBER NULL,
 FORMCODE NUMBER	NOT NULL,
 
 CONSTRAINT MBOXNO_FK FOREIGN KEY (MYBOXCODE, EMPNO) REFERENCES MYBOXLIST ON DELETE CASCADE,
 CONSTRAINT MBDOCNO_FK FOREIGN KEY (DOCNO) REFERENCES DRAFT ON DELETE CASCADE,
 CONSTRAINT MBFORMCODE_FK FOREIGN KEY (FORMCODE) REFERENCES FORMBOX ON DELETE SET NULL
);

COMMENT ON COLUMN MYBOX.MYBOXCODE IS '내문서함코드';
COMMENT ON COLUMN MYBOX.EMPNO IS '사번';
COMMENT ON COLUMN MYBOX.DOCNO IS '문서번호';
COMMENT ON COLUMN MYBOX.FORMCODE IS '문서양식코드';

INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '일반 기안서', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '휴가 신청서', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '기타1', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '기타2', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '기타3', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '기타4', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '공용', '기타5', '공용 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '업무일지', '직원 업무일지', '업무일지 양식');
INSERT INTO FORMBOX VALUES (FORMCODE_SEQ.NEXTVAL, '업무일지', '관리자 업무일지', '업무일지 양식');

-- 업무일지 테이블 
CREATE TABLE BUSINESSLOG (
 LOGNO NUMBER,
 EMPNO VARCHAR2(20)	 NOT NULL,
 FORMCODE NUMBER	NOT NULL,
 DOCTITLE VARCHAR2(150)	NOT NULL,
 DOCCONTENT LONG	NOT NULL,
 ORIGINFILE VARCHAR2(100)	NULL,
 RENAMEFILE VARCHAR2(100)	NULL,
 WRITEDATE DATE	DEFAULT SYSDATE	NOT NULL,
 PROGRESS CHAR(1)	DEFAULT 0	NOT NULL,
 APPROVER VARCHAR2(1000) NULL,
 APPDATE DATE DEFAULT SYSDATE NULL,
 FEEDBACK VARCHAR2(2000)	NULL,
 
CONSTRAINT LOGNO_PK PRIMARY KEY (LOGNO),
CONSTRAINT LEMPNO_FK FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE ON DELETE SET NULL,
CONSTRAINT BFORMCODE_FK FOREIGN KEY (FORMCODE) REFERENCES FORMBOX ON DELETE SET NULL,
CONSTRAINT BEMPNO_FK FOREIGN KEY (APPROVER) REFERENCES EMPLOYEE ON DELETE SET NULL
);

COMMENT ON COLUMN BUSINESSLOG.LOGNO IS '문서번호';
COMMENT ON COLUMN BUSINESSLOG.EMPNO IS '기안자';
COMMENT ON COLUMN BUSINESSLOG.FORMCODE IS '문서양식코드';
COMMENT ON COLUMN BUSINESSLOG.DOCTITLE IS '문서제목';
COMMENT ON COLUMN BUSINESSLOG.DOCCONTENT IS '문서내용';
COMMENT ON COLUMN BUSINESSLOG.ORIGINFILE IS '원래파일명';
COMMENT ON COLUMN BUSINESSLOG.RENAMEFILE IS '변경된파일명';
COMMENT ON COLUMN BUSINESSLOG.WRITEDATE IS '문서작성날짜';
COMMENT ON COLUMN BUSINESSLOG.PROGRESS IS '문서진행상태';
COMMENT ON COLUMN BUSINESSLOG.APPROVER IS '결재자';
COMMENT ON COLUMN BUSINESSLOG.APPDATE IS '최종결재날짜';
COMMENT ON COLUMN BUSINESSLOG.FEEDBACK IS '첨삭및의견';



 
INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'10001', 
'100', 
'기안1', 
'기안내용1', 
NULL, 
NULL, 
SYSDATE, 
'3',  
'admin',
'보류함',
'19/12/01',
NULL,
'30001, 50001'
);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'110', 
'기안2', 
'기안내용2', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'admin',
NULL,
'19/12/01',
NULL,
'70001');

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'10001', 
'100', 
'기안3', 
'기안내용3', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'admin',
NULL,
'19/12/01',
NULL,
'30001,70001');


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'50001', 
'170', 
'기안4', 
'기안내용4', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'admin',
NULL,
'19/12/31',
NULL,
'30001,10001');


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'70001', 
'110', 
'기안5', 
'기안내용5', 
NULL, 
NULL, 
SYSDATE, 
'2', 
'10001,30001,admin',
'피드백',
'19/12/01',
NULL,
'10001, 50001');


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'100', 
'기안6', 
'기안내용6', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'admin',
'승인함',
'19/12/01',
NULL,
'10001,50001,70001');

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'30001', 
'110', 
'기안7', 
'기안내용7', 
NULL, 
NULL, 
SYSDATE, 
'2', 
'50001,admin',
'반려함',
'19/12/08',
NULL,
'50001,10001');

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'50001', 
'170', 
'기안8', 
'기안내용8', 
NULL, 
NULL, 
SYSDATE, 
'1', 
'admin',
NULL,
'19/12/25',
NULL,
NULL);

INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'70001', 
'170', 
'기안9', 
'기안내용9', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'admin',
NULL,
'19/12/01',
NULL,
NULL);


INSERT INTO DRAFT VALUES (
DOCNO_SEQ.NEXTVAL, 
'50001', 
'120', 
'기안10', 
'기안내용10', 
NULL, 
NULL, 
SYSDATE, 
'0', 
'admin',
NULL,
'19/12/01',
NULL,
'30001');


INSERT INTO MYBOXLIST VALUES (
1, '10001', '새문서함1'
);
INSERT INTO MYBOXLIST VALUES (
2, '10001', '새문서함2'
);
 
INSERT INTO MYBOX VALUES (
'1', '10001', 1, 100
);
INSERT INTO MYBOX VALUES (
'1', '10001', 2, 110
);
INSERT INTO MYBOX VALUES (
'2', '10001', 3, 100
);
COMMIT;