/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-07 14:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.employee.maintenance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BillListDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 타이틀 시작 -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div id=\"breadcrumb\" class=\"col-xs-12\">\r\n");
      out.write("\t\t<!-- 삼디다스 버튼 -->\r\n");
      out.write("\t\t<a href=\"#\" class=\"show-sidebar\"> <i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<ol class=\"breadcrumb pull-left\">\r\n");
      out.write("\t\t\t<!-- 첫번째 타이틀 시작 -->\r\n");
      out.write("\t\t\t<li><a href=\"index.html\">관리비</a></li>\r\n");
      out.write("\t\t\t<!-- 두번째 하위 메뉴 시작 -->\r\n");
      out.write("\t\t\t<li><a href=\"#\">고지서조회</a></li>\r\n");
      out.write("\t\t\t<!-- 세번째 하위 메뉴 시작 -->\r\n");
      out.write("\t\t\t<!--li><a href=\"#\">부과항목등록</a></li-->\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 타이틀 끝 -->\r\n");
      out.write("<!-- 고지서목록 -->\r\n");
      out.write("<div class=\"bs-callout bs-callout-info\" id=\"callout-tabs-extends-component\">\r\n");
      out.write("    <h4>관리비 납입영수증</h4>\r\n");
      out.write(" </div>\r\n");
      out.write(" <br>\r\n");
      out.write("<table\r\n");
      out.write("\tclass=\"table table-bordered\">\r\n");
      out.write("\t<thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"2\" class=\"danger\">전기 에너지</th>\r\n");
      out.write("\t\t\t<th>000000원</th>\r\n");
      out.write("\t\t\t<th colspan=\"2\" class=\"danger\">열 에너지</th>\r\n");
      out.write("\t\t\t<th>000000원</th>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t</thead>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"text-align:right;\">세대전기료</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"text-align:right;\">난방사용료</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"text-align:right;\">공동전기료</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"text-align:right;\">온수사용료</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"text-align:right;\">Tv수신료</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"3\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"\">\r\n");
      out.write("\t\t\t<th colspan=\"6\" class=\"primary\">전년동월과 당월비교</th>\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"active\"></th>\r\n");
      out.write("\t\t\t<th>전년 사용량</th>\r\n");
      out.write("\t\t\t<th>사용요금</th>\r\n");
      out.write("\t\t\t<th>당월 사용량</th>\r\n");
      out.write("\t\t\t<th>사용요금</th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"active\">전기</th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"active\">온수</th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"active\">수도</th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"active\">난방</th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"2\" style=\"font-size:13pt; text-align:center; color:black; background:#fff;\">2019년 9월</th>\r\n");
      out.write("\t\t\t<th colspan=\"2\" style=\"font-size:13pt; text-align:center; color:black; background:#fff;\">101동101호</th>\r\n");
      out.write("\t\t\t<th colspan=\"2\" style=\"font-size:13pt; text-align:center; color:black; background:#fff;\">홍길동 귀하</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>일반관리비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<th colspan=\"2\" class=\"warning\">전기사용료</th>\r\n");
      out.write("\t\t\t<th>당월부과액</th>\r\n");
      out.write("\t\t\t<td>2222222원</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>청소비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td>세대전기료</td>\r\n");
      out.write("\t\t\t<td>222222원</td>\r\n");
      out.write("\t\t\t<th>미납액</th>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>소독비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td>공동전기료</td>\r\n");
      out.write("\t\t\t<td>222222원</td>\r\n");
      out.write("\t\t\t<th>미납연체료</th>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>승강기유지비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td>Tv수신료</td>\r\n");
      out.write("\t\t\t<td>222222원</td>\r\n");
      out.write("\t\t\t<th>납기후 연체료</th>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>수선유지비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<th colspan=\"4\" class=\"active\"></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>장기수선충당금</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<th colspan=\"2\" class=\"primary\">수도사용료</th>\r\n");
      out.write("\t\t\t<th colspan=\"2\">관리비 납입계좌번호</th>\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>음식물수거료</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td>세대수도료</td>\r\n");
      out.write("\t\t\t<td>222222원</td>\r\n");
      out.write("\t\t\t<td>신한은행</td>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>경비비</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td>공동수도료</td>\r\n");
      out.write("\t\t\t<td>222222원</td>\r\n");
      out.write("\t\t\t<td>국민은행</td>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>화재보험료</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\" class=\"active\"></td>\r\n");
      out.write("\t\t\t<td>하나은행</td>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>위탁관리수수료</td>\r\n");
      out.write("\t\t\t<td>22222원</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\" class=\"active\"></td>\r\n");
      out.write("\t\t\t<td>우리은행</td>\r\n");
      out.write("\t\t\t<td>0</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"danger\" style=\"text-align:center;\">납기내</th>\t\t\t\t\r\n");
      out.write("\t\t\t<th rowspan=\"2\" colspan=\"2\" style=\"font-size:20pt; text-align:center; line-height:40pt;\">34588원</th> \r\n");
      out.write("\t\t\t<th class=\"danger\" style=\"text-align:center;\">납기후</th>\r\n");
      out.write("\t\t\t<th rowspan=\"2\" colspan=\"2\" style=\"font-size:20pt; text-align:center; line-height:40pt;\">34588원</th> \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th class=\"active\" style=\"text-align:center;\">까지</th>\t\r\n");
      out.write("\t\t<th class=\"active\" style=\"text-align:center;\">까지</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
