/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-05 09:19:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user.bill;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import maintenance.model.vo.UserBill;
import java.util.ArrayList;
import java.util.*;
import java.text.*;
import aptuser.model.vo.Aptuser;

public final class userBillList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/user/bill/../userheader.jsp", Long.valueOf(1572945545184L));
    _jspx_dependants.put("/views/user/bill/../userfooter.jsp", Long.valueOf(1572251992295L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("aptuser.model.vo.Aptuser");
    _jspx_imports_classes.add("maintenance.model.vo.UserBill");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<UserBill> ublist = (ArrayList<UserBill>) request.getAttribute("list");
	UserBill ubill = (UserBill) request.getAttribute("ubill");
	int currentPage = (Integer) request.getAttribute("currentPage");
	int beginPage = (Integer) request.getAttribute("beginPage");
	int endPage = (Integer) request.getAttribute("endPage");
	int maxPage = (Integer) request.getAttribute("maxPage");
	String months = (String) request.getAttribute("months");

      out.write('\r');
      out.write('\n');

DecimalFormat df = new DecimalFormat("###,###");
SimpleDateFormat ft = new SimpleDateFormat ( "yyyy년 M월");

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>HiAPTU</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<!-- Bootstrap CSS File -->\r\n");
      out.write("<link href=\"/hiapt/resources/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries CSS Files -->\r\n");
      out.write("<link href=\"/hiapt/resources/css/prettyphoto.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/hiapt/resources/css/hoverex-all.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/hiapt/resources/css/jetmenu.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/hiapt/resources/css/owl-carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet File -->\r\n");
      out.write("<link href=\"/hiapt/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hiapt/resources/css/blue.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

   Aptuser aptuser = (Aptuser)session.getAttribute("aptuser");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"topbar clearfix\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"col-lg-12 text-right\">\r\n");
      out.write("        <div class=\"social_buttons\">\r\n");
      out.write("          \r\n");
      out.write("          <span style=\"width:66px;padding: 16px;font-size: 16px;\">");
      out.print( aptuser.getUserName() );
      out.write("</span>\r\n");
      out.write("          <span class=\"at_bar\">|</span><a href=\"/hiapt/uout\">로그아웃 </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end topbar -->\r\n");
      out.write("\r\n");
      out.write("  <header class=\"header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"site-header clearfix\">\r\n");
      out.write("        <div class=\"col-lg-3 col-md-3 col-sm-12 title-area\">\r\n");
      out.write("          <div class=\"site-title\" id=\"title\">\r\n");
      out.write("            <a href=\"/hiapt/login.jsp\" title=\"\">\r\n");
      out.write("              <h2>Hi<span>APT</span></h2>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- title area -->\r\n");
      out.write("        <div class=\"col-lg-9 col-md-12 col-sm-12\">\r\n");
      out.write("          <div id=\"nav\" class=\"right\">\r\n");
      out.write("            <div class=\"container clearfix\">\r\n");
      out.write("              <ul id=\"jetmenu\" class=\"jetmenu blue\">  \r\n");
      out.write("               \t <li><a href=\"#\">관리비조회</a>\r\n");
      out.write("                   <ul class=\"dropdown\">                    \r\n");
      out.write("                    <ul class=\"dropdown\">   \t\t\t\t   \r\n");
      out.write("                    <li><a href=\"/hiapt/ublist\">관리비조회</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/bill/payment.jsp\">관리비결제</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/bill/ReceiptList.jsp\">납부내역조회</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/bill/paySuccess.jsp\">결제완료</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/bill/payFail.jsp\">결제실패</a></li>                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\">관리비결제</a></li>\r\n");
      out.write("                <li><a href=\"/hiapt/co.list\">민원접수</a></li>\r\n");
      out.write("                <li><a href=\"/hiapt/vo.list\">주민투표</a></li>\r\n");
      out.write("                <li><a href=\"/hiapt/no.list\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"/hiapt/bo.list\">자유게시판</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- nav -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- title area -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- site header -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- end header -->\r\n");
      out.write("  <!-- 세대주 머리부분 공통부분 복사해서 쓰세요 끝 =============================================================================== -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 본문 타이틀 시작 구성 타이틀 부분 복사 시작==================================================================================-->\r\n");
      out.write("<section class=\"post-wrapper-top\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/hiapt/index2.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li>관리비조회</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<sapn class=\"text-info\">");
      out.print(aptuser.getUserName());
      out.write("</sapn>\r\n");
      out.write("\t\t\t\t&nbsp;님의 관리비조회\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\" style=\"margin-top: 53px;\">\r\n");
      out.write("\t\t\t<!-- search -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 부과년월 검색 -->\r\n");
      out.write("\t\t\t\t <form action=\"/hiapt/ublist\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"search\" value=\"months\" /> \r\n");
      out.write("\t\t\t\t\t부과년월&nbsp;\r\n");
      out.write("\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"month\" name=\"months\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t\t\t</label> <input type=\"submit\" value=\"검색\" onclick=\"sendIt()\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\" style=\"margin-bottom: 5px;\r\n");
      out.write("    padding-bottom: 7px;\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- / end div .search-bar -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- end post-wrapper-top -->\r\n");
      out.write("<!-- 본문 타이틀 시작 구성 타이틀 부분 복사 끝==================================================================================-->\r\n");
      out.write("<!--  -->\r\n");
      out.write("<section class=\"section1\">\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 검색버튼 사용시  -->\r\n");
      out.write("\t\t");
 if(months != null){ 
      out.write("\r\n");
      out.write("\t\t\t<!-- <div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"당월고지서인쇄\" id=\"submit\" class=\"button\">\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table table-striped\" data-effect=\"fade\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>고지서번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>당월부과액</th>\r\n");
      out.write("\t\t\t\t\t\t<th>미납액</th>\r\n");
      out.write("\t\t\t\t\t\t<th>미납연체료</th>\r\n");
      out.write("\t\t\t\t\t\t<th>납기내 금액</th>\r\n");
      out.write("\t\t\t\t\t\t<th>납기후 금액</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 0; i < ublist.size(); i++) {
							UserBill b = ublist.get(i);
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><a href='/hiapt/ubdt?merchantUid=");
      out.print( b.getMerchantUid() );
      out.write('\'');
      out.write('>');
      out.print(b.getMerchantUid());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( df.format(b.getAmount()));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( df.format(b.getArrears()));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( df.format(b.getArrearsFine()));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( df.format(b.getBeforeAmount()));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print( df.format(b.getAfterAmount()));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t<div class=\"paging_simple_numbers\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/ublist?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if ((beginPage - 10) < 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/ublist?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page=");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if ((beginPage - 10) <= 9) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/ublist?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							for (int p = beginPage; p <= endPage; p++) {
										if (p == currentPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active next\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page=");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
									}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if ((endPage + 10) > maxPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/ublist?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div><!-- paging_simple_numbers -->\r\n");
      out.write("\t\t\t</div><!-- .col-sm-12 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 } else if(months == null){ 
      out.write("\r\n");
      out.write("\t\t\t<!--  검색 버튼 비사용시 먼저 뜨는 화면 -->\r\n");
      out.write("\t\t\t<div class=\"content col-xs-12 clearfix\" id=\"userBill\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/hiapt/ubtop1\",\r\n");
      out.write("\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t\t//문자열을 json 배열 객체로 바꿈\r\n");
      out.write("\t\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar values = \"\"; // 빈 값을 생성\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfor ( var i in json.ulist) { //로그인되어 있으면 페이지 번호를 연결해서 상세보기로 넘어가게\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvalues += \"<div class='general-title text-center'><h3>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].billYearMonth.slice(0,7)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"월분</h3><p>납부마감일 : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].cutoffDate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</p><hr></div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<table class='table table-striped'><tr><th scope='col'>고지서번호</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].merchantUid\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"&nbsp;&nbsp; <a class='button small' href='/hiapt/ubdt?merchantUid=\"+ json.ulist[i].merchantUid \r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"&page=1'>당월고지서 인쇄</a>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</a></td><tr><th scope='col'>당월부과액</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].amount\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"원</a></td><tr><th scope='col'>미납액</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].arrears\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"원</td><tr><th scope='col'>미납 연체료</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].arrearsFine\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"원</td><tr><th scope='col'>납기내 금액</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].beforeAmount\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"원</td><tr><th scope='col'>납기후 금액</th><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ json.ulist[i].afterAmount\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"원</td></tr></table>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t    +\" <ul class='pager'><li class='previous'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t    + \"<a href='/hiapt/views/user/maintenance/ReceiptList.jsp'>← 납부내역조회</a></li>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t    + \"<li class='next'><a href='/hiapt/paylist?merchantUid=\" + json.ulist[i].merchantUid + \"&page=1'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t    + \"아파트관리비 납부하기 →</a></li></ul>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#userBill\").html($(\"#userBill\").html() + values);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \", \" + errorThrown);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});// end top1\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end container -->\r\n");
      out.write("</section>\r\n");
      out.write("<!-- end section -->\r\n");
      out.write("\r\n");
      out.write("<!--  /// 본문 끝//////  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 세대주 아래 공통부분 복사해서 쓰세요 시작 =============================================================================== --> \r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">  \r\n");
      out.write("    <ul class=\"footer-menu\">\r\n");
      out.write("      <li class=\"ma-1\"><a href=\"#\"> 회사소개 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span><a href=\"#\"> 이용약관 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span><a href=\"#\"> 개인정보처리방침 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span> Copyright &copy; 2019 - All rights reserved.</li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- end footer -->\r\n");
      out.write("  <div class=\"dmtop\">Scroll to Top</div>\r\n");
      out.write(" \r\n");
      out.write("  <!-- JavaScript Libraries -->\r\n");
      out.write("  <script src=\"/hiapt/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/prettyphoto.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/hoverdir.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/jetmenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main Javascript File -->\r\n");
      out.write("  <script src=\"/hiapt/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
