/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-15 16:29:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aptuser.model.vo.Aptuser;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/user/userfooter.jsp", Long.valueOf(1571156908936L));
    _jspx_dependants.put("/views/user/userheader.jsp", Long.valueOf(1571156908944L));
    _jspx_dependants.put("/views/user/userhead.html", Long.valueOf(1571156908940L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("aptuser.model.vo.Aptuser");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<!-- head 시작  -->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>HiAPTU</title>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write(" <!--  <link href=\"img/favicon.png\" rel=\"icon\"> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Ruda:400,900,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap CSS File -->\r\n");
      out.write("  <link href=\"/hiapt/resources/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Libraries CSS Files -->\r\n");
      out.write("  <link\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/hiapt/resources/css/prettyphoto.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/hiapt/resources/css/hoverex-all.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/hiapt/resources/css/jetmenu.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/hiapt/resources/css/owl-carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Stylesheet File -->\r\n");
      out.write("  <link href=\"/hiapt/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hiapt/resources/css/blue.css\">\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<!-- head 끝  -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navi 시작  -->\r\n");
      out.write('\r');
      out.write('\n');

   Aptuser aptuser = (Aptuser)session.getAttribute("aptuser");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"topbar clearfix\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"col-lg-12 text-right\">\r\n");
      out.write("        <div class=\"social_buttons\">\r\n");
      out.write("          \r\n");
      out.write("          <span style=\"width:66px;padding: 16px;font-size: 16px;\">");
      out.print( aptuser.getUserName() );
      out.write("</span>\r\n");
      out.write("          <span class=\"at_bar\">|</span><a href=\"/hiapt/uout\">로그아웃 </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end topbar -->\r\n");
      out.write("\r\n");
      out.write("  <header class=\"header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"site-header clearfix\">\r\n");
      out.write("        <div class=\"col-lg-3 col-md-3 col-sm-12 title-area\">\r\n");
      out.write("          <div class=\"site-title\" id=\"title\">\r\n");
      out.write("            <a href=\"/hiapt/login.jsp\" title=\"\">\r\n");
      out.write("              <h2>Hi<span>APT</span></h2>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- title area -->\r\n");
      out.write("        <div class=\"col-lg-9 col-md-12 col-sm-12\">\r\n");
      out.write("          <div id=\"nav\" class=\"right\">\r\n");
      out.write("            <div class=\"container clearfix\">\r\n");
      out.write("              <ul id=\"jetmenu\" class=\"jetmenu blue\">\r\n");
      out.write("                <!--li class=\"active\"><a href=\"index.html\">Home</a>\r\n");
      out.write("                </li-->\r\n");
      out.write("                <li><a href=\"#\">샘플들</a>\r\n");
      out.write("                   <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/contact.html\">샘플1</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/sample.html\">샘플2</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/404.html\">샘플3</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/about.html\">샘플4</a></li>  \r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/service.html\">샘플5</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/support.html\">샘플6</a></li>  \r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/testimonials.html\">샘플7</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/sample/fullwidth.html\">샘플8</a></li>                      \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\">관리비조회</a>\r\n");
      out.write("                   <ul class=\"dropdown\">                    \r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/maintenance/BillList.jsp\">관리비조회</a></li>\r\n");
      out.write("                    <li><a href=\"/hiapt/views/user/maintenance/ReceiptList.jsp\">납부내역조회</a></li>                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\">관리비결제</a></li>\r\n");
      out.write("                <li><a href=\"#\">민원접수</a></li>\r\n");
      out.write("                <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"#\">주민투표</a></li>\r\n");
      out.write("                <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- nav -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- title area -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- site header -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- end header -->\r\n");
      out.write("  <!-- 세대주 머리부분 공통부분 복사해서 쓰세요 끝 =============================================================================== -->");
      out.write("\r\n");
      out.write("<!-- navi 끝  -->\r\n");
      out.write("\r\n");
      out.write("<!-- /// 본문 시작////// -->\r\n");
      out.write("\r\n");
      out.write("  <section id=\"intro\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"ror\">\r\n");
      out.write("        <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("          <h1>하이 프리미엄,<br> 이곳은 Hi아파트 입니다.</h1>\r\n");
      out.write("          <p>화창한 날입니다. 그리고 전 그걸 볼수가 없죠.<br>It’s a beautiful day and I can’t see it.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <section class=\"section1\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"col-lg-4 col-md-4 col-sm-4\">\r\n");
      out.write("        <div class=\"servicebox text-center\">\r\n");
      out.write("          <div class=\"service-icon\">\r\n");
      out.write("            <div class=\"dm-icon-effect-1\" data-effect=\"slide-left\">\r\n");
      out.write("              <a href=\"#\" class=\"\"> <i class=\"active dm-icon fa fa-search fa-3x\"></i> </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"servicetitle\">\r\n");
      out.write("              <h4>관리비조회</h4>\r\n");
      out.write("              <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>고지서보다 빠르게, 인터넷으로 편하게, <br>지나달과 작년 같은 달과도 비교하고<br> 항목마다도 비교해 볼 수 있는 똑똑한 조회!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- service-icon -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- servicebox -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- large-4 -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-4 col-sm-4\">\r\n");
      out.write("        <div class=\"servicebox text-center\">\r\n");
      out.write("          <div class=\"service-icon\">\r\n");
      out.write("            <div class=\"dm-icon-effect-1\" data-effect=\"slide-bottom\">\r\n");
      out.write("              <a href=\"#\" class=\"\"> <i class=\"active dm-icon fa fa-credit-card fa-3x\"></i> </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"servicetitle\">\r\n");
      out.write("              <h4>관리비결제</h4>\r\n");
      out.write("              <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>언제 어디서나 편안하게<br> 자동이체로 납부하는 세대의 관리비 할인법 <br> 다음달 관리비 차감하자!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- service-icon -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- servicebox -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- large-4 -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-4 col-sm-4\">\r\n");
      out.write("        <div class=\"servicebox text-center\">\r\n");
      out.write("          <div class=\"service-icon\">\r\n");
      out.write("            <div class=\"dm-icon-effect-1\" data-effect=\"slide-right\">\r\n");
      out.write("              <a href=\"#\" class=\"\"> <i class=\"active dm-icon fa fa-pencil-square-o fa-3x\"></i> </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"servicetitle\">\r\n");
      out.write("              <h4>민원접수</h4>\r\n");
      out.write("              <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>작은 소리도 크게 듣겠습니다.  <br> 주민여러분과 함께 하는 온라인 단일창구 입니다.<br> 200가지 행복</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- service-icon -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- servicebox -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- large-4 -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- end section -->\r\n");
      out.write("  \r\n");
      out.write("  <!--  /// 본문 끝//////  -->\r\n");
      out.write("\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 세대주 아래 공통부분 복사해서 쓰세요 시작 =============================================================================== --> \r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">  \r\n");
      out.write("    <ul class=\"footer-menu\">\r\n");
      out.write("      <li class=\"ma-1\"><a href=\"#\"> 회사소개 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span><a href=\"#\"> 이용약관 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span><a href=\"#\"> 개인정보처리방침 </a></li>\r\n");
      out.write("      <li><span class=\"at_bar\">|</span> Copyright &copy; 2019 - All rights reserved.</li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- end footer -->\r\n");
      out.write("  <div class=\"dmtop\">Scroll to Top</div>\r\n");
      out.write(" \r\n");
      out.write("  <!-- JavaScript Libraries -->\r\n");
      out.write("  <script src=\"/hiapt/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/prettyphoto.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/hoverdir.js\"></script>\r\n");
      out.write("  <script src=\"/hiapt/resources/js/jetmenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main Javascript File -->\r\n");
      out.write("  <script src=\"/hiapt/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- footer 끝  -->\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
