/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-05 05:55:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import employee.model.vo.Employee;

public final class schedulemain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/schedule/../../common/empfooter.html", Long.valueOf(1571394836959L));
    _jspx_dependants.put("/views/common/schedule/../../common/topbutton.html", Long.valueOf(1571652039501L));
    _jspx_dependants.put("/views/common/schedule/../empTopNavi.jsp", Long.valueOf(1572932389984L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("employee.model.vo.Employee");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	Employee emp = (Employee)session.getAttribute("employee");

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!--복사 시작 ////////////////////////////--------------------->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>HIAPTProject</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"/hiapt/resources/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"/hiapt/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/hiapt/resources/css/basic.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!--// css or jQuery or javaScript 삽입 부분    -->\r\n");
      out.write("<style>\r\n");
      out.write(".check {\r\n");
      out.write("display: inline-block !important;\r\n");
      out.write("}\r\n");
      out.write("table > tbody> tr.intable, table > tbody> tr.intable > td{\r\n");
      out.write("height:7rem;\r\n");
      out.write("cellspacing:0;\r\n");
      out.write("cellpadding:5;\r\n");
      out.write("align:center;\r\n");
      out.write("table-layout : fixed;\r\n");
      out.write("padding:0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

	Calendar tDay = Calendar.getInstance();//캘린더 객체 생성
	int cy = tDay.get(Calendar.YEAR);//객체에서 년도 변수에 저장 
	int cm = tDay.get(Calendar.MONTH);//객체에서 월 변수에 저장
	int cd = tDay.get(Calendar.DATE);//객체에서 일 변수에 저장
    String Year = request.getParameter("year");
	String Month = request.getParameter("month");

	int year, month;
	if(Year == null && Month == null){
		year = cy;
		month = cm;
	}else{
		year = Integer.parseInt(Year);
		month = Integer.parseInt(Month);
		if(month < 0){
			month = 11; 
			year = year-1;
		}			
		if(month >11){
			month = 0;
			year = year+1;
		}
	}
tDay.set(year, month, 1);//현재 년월 1일을 객체에 저장

int start = tDay.get(Calendar.DAY_OF_WEEK);//현재 년월 1일의 요일을 yo에 저장 일요일 : 1, 월요일:2, 화요일:3..
int lastday = tDay.getActualMaximum(Calendar.DAY_OF_MONTH);//매월이 가질 수 있는 값의 최대값을 마지막일자로 저장함

      out.write("\r\n");
      out.write("var div=\"\";\r\n");
      out.write("var str=\"\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"td:nth-child(1)\").css(\"color\",\"red\");\r\n");
      out.write("\t$(\"td:nth-child(7)\").css(\"color\",\"blue\");\r\n");
      out.write("\t$(\".intable\").css(\"text-align\",\"right\").css(\"valign\",\"top\");\r\n");
      out.write("\tvar writer ='");
      out.print( emp.getEmpNo());
      out.write("';\r\n");
      out.write("\tvar year = ");
      out.print(year);
      out.write("\r\n");
      out.write("\tvar mon = ");
      out.print(month);
      out.write("\r\n");
      out.write("\tvar month = Number(mon)+1;\r\n");
      out.write("\tvar day;\r\n");
      out.write("\t//일정 db에서 끌어오기\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/hiapt/schlist?year=\"+year+\"&month=\"+month+\"&wr=\"+writer,\r\n");
      out.write("\t\ttype : \"get\",\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar value = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar onlySday = \"\";\r\n");
      out.write("\t\t\tvar onlyEday = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\t//가져온 json 변수에 담기\r\n");
      out.write("\t\t\t\tvalue += \r\n");
      out.write("\t\t\t\tjson.list[i].cnum+\"<br>\"+\r\n");
      out.write("\t\t\t\tdecodeURIComponent(json.list[i].ctitle).replace(/\\+/gi,\" \")+\"<br>\"+\t\t\t\t\r\n");
      out.write("\t\t\t\tdecodeURIComponent(json.list[i].color).replace(/\\+/gi,\" \")+\"<br>\"+\r\n");
      out.write("\t\t\t\tdecodeURIComponent(json.list[i].cwriter).replace(/\\+/gi,\" \")+\"<br>\"+\r\n");
      out.write("\t\t\t\tjson.list[i].cstart.split(\"-\")+\"<br>\"+\r\n");
      out.write("\t\t\t\tjson.list[i].cend.split(\"-\")+\"<br>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//시작일자 나눠서 변수에 담기\t\r\n");
      out.write("\t\t\t\tvar startdays = json.list[i].cstart.split(\"-\");\r\n");
      out.write("\t\t\t\tvar enddays = json.list[i].cend.split(\"-\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//일(day)만 String 변수에 담기\r\n");
      out.write("\t\t\t\tonlySday += startdays[2]+\",\";\r\n");
      out.write("\t\t\t\tonlyEday += enddays[2]+\",\";\r\n");
      out.write("\t\t\t\t//일(dat)만 array 변수에 담기\r\n");
      out.write("\t\t\t\tvar sDlist = onlySday.split(\",\");\r\n");
      out.write("\t\t\t\tvar eDlist = onlyEday.split(\",\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(sDlist[i] == eDlist[i]){//시작일자 끝일자 동일하다면 \r\n");
      out.write("\t\t\t\t\tvar div = \"<div class='div' id='\"+\r\n");
      out.write("\t\t\t\t\tjson.list[i].cnum+\r\n");
      out.write("\t\t\t\t\t\"'style='z-index:1000; cursor:pointer; diplay:block; color:#ffffff; background-color:\"+\r\n");
      out.write("\t\t\t\t\tdecodeURIComponent(json.list[i].color).replace(/\\+/gi,\" \")+\";'>\"+\r\n");
      out.write("\t\t\t\t\tdecodeURIComponent(json.list[i].ctitle).replace(/\\+/gi,\" \")+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(sDlist[i].charAt(0)==0){\r\n");
      out.write("\t\t\t\t\t\tsDlist[i] = sDlist[i].substr(1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#\"+sDlist[i]).html($(\"#\"+sDlist[i]).html()+div);\r\n");
      out.write("\t\t\t\t}else{//시작일자와 끝일자 동일하지 않다면\r\n");
      out.write("\t\t\t\t\tvar div = \"<div class='div' id='\" + json.list[i].cnum+\r\n");
      out.write("\t\t\t\t\t\"'style='z-index:1000; cursor:pointer; diplay:block; color:#ffffff; background-color:\"+\r\n");
      out.write("\t\t\t\t\tdecodeURIComponent(json.list[i].color).replace(/\\+/gi,\" \")+\";'>\"+\r\n");
      out.write("\t\t\t\t\tdecodeURIComponent(json.list[i].ctitle).replace(/\\+/gi,\" \")+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(sDlist[i].charAt(0)==0){\r\n");
      out.write("\t\t\t\t\t\tsDlist[i] = sDlist[i].substr(1);\r\n");
      out.write("\t\t\t\t\t}else if(eDlist[i].charAt(0)==0){\r\n");
      out.write("\t\t\t\t\t\teDlist[i] = eDlist[i].substr(1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#\"+sDlist[i]).html($(\"#\"+sDlist[i]).html()+div);\r\n");
      out.write("\t\t\t\t\t$(\"#\"+eDlist[i]).html($(\"#\"+eDlist[i]).html()+div);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}//for in문 종료\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar sslist = onlySday.split(\",\");\r\n");
      out.write("\t\t\tfor(var i in sslist){\r\n");
      out.write("\t\t\t\tconsole.log(sslist[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//받아온 json 출력\r\n");
      out.write("\t\t\t$(\"#test\").html(value+\"<br>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"error : \"+jqXHR+\", \"+textStatus+\", \"+errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})//ajax 종료\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".intable\").click(function(event){\r\n");
      out.write("\t\tif($(event.target).is(\".div\")){//클릭한 타겟이 div 클래스라면\r\n");
      out.write("\t\t\tdiv=$(event.target).attr(\"id\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar url =\"/hiapt/schdetail?snum=\"+div;\r\n");
      out.write("\t\t\tvar name = \"schedule detail\";\r\n");
      out.write("\t\t\tvar option = \"width=600, height=600, top= 100, left = 200, location=no\";\r\n");
      out.write("\t\t\twindow.open(url, name, option );\r\n");
      out.write("\t\t}else if($(event.target).is(\"td\")){\r\n");
      out.write("\t\t\tday=$(event.target).attr(\"id\");\r\n");
      out.write("\t\t\tif(day != null){\r\n");
      out.write("\t\t\t\tif(month.toString().length == 1){\r\n");
      out.write("\t\t\t\t\tmonth = \"0\"+month.toString();\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\tif(day.length == 1){\r\n");
      out.write("\t\t\t\t\tday = \"0\"+day;\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tstr = year+\"-\"+month+\"-\"+day;\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(str);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar url =\"scheduleInsert.jsp?y=\"+year+\"&m=\"+month+\"&d=\"+day;\r\n");
      out.write("\t\t\t\tvar name = \"schedule insert\";\r\n");
      out.write("\t\t\t\tvar option = \"width=600, height=600, top= 100, left = 200, location=no\";\r\n");
      out.write("\t\t\t\tpopup = window.open(url, name, option );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#schin\").on(\"click\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href=\"/hiapt/views/common/schedule/schedulemain.jsp?year=");
      out.print(cy);
      out.write("&month=");
      out.print(cm);
      out.write("\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("});//도큐멘트 리드\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 시작  --> \r\n");
      out.write("\t\t<ul\r\n");
      out.write("\t\t\tclass=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("\t\t\tid=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("<!-- 스마일 로고 -->\r\n");
      out.write("\t\t\t<a class=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("\t\t\t\thref=\"/hiapt/login.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("\t\t\t\t\tHIAPT <sup>2</sup>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("<!-- 왼쪽 메뉴바 시작 -->\r\n");
      out.write("<!-- ============================================================= -->\t\t\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 메일 시작 -->\r\n");
      out.write("\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\tdata-toggle=\"collapse\" data-target=\"#mail\" aria-expanded=\"true\"\r\n");
      out.write("\t\taria-controls=\"collapseTwo\"> <i class=\"fas fa-fw fa-envelope-open\"></i>\r\n");
      out.write("\t\t\t<span>메일</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t\t<div id=\"mail\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("\t\t\tdata-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/mail/writemail.jsp\">메일쓰기</a>\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/views/emp/mail/selfwritemail.jsp\">내게쓰기</a></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/amlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">전체메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/rlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">받은메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/smlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">보낸메일함</a></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/tmlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">임시보관함</a></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/selfmlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">내게 쓴\r\n");
      out.write("\t\t\t\t\t메일함</a> <a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/wmlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("\">휴지통</a>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div class=\"dropdown\" style=\"display:inline-block;\">\r\n");
      out.write("  \t\t\t\t\t\t\t&nbsp;<button class=\"btn btn-link btn-sm dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\">\r\n");
      out.write("  \t\t\t\t\t\t\t</button><span>내 메일함</span>&nbsp;\r\n");
      out.write("  \t\t\t\t\t\t\t<div id=\"a\" class=\"dropdown-menu\">  \t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <button id=\"insert\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></button> -->\r\n");
      out.write("\t\t\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-plus fa-fw fa-envelope-open\"></i>  \r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" style=\"display:inline-block;\">내 메일함</a>&nbsp;<a href=\"#\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메일 끝 -->\r\n");
      out.write("<!-- ====================================================================================== -->\r\n");
      out.write("<!-- ====================================================================================== -->\t\t\t\r\n");
      out.write("<!--인사정보 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t      \t\r\n");
      out.write("\t\t\t");
 if(emp != null && emp.getEmpId().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/employee/empEnroll.jsp\">직원등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/empdetail?empno=");
      out.print( emp.getEmpNo() );
      out.write("\">내정보보기</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/user/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- 인사정보 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--전자결재 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t\t");
 if(emp != null && emp.getEmpNo().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist.ad?page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby.ad?page=1\">전자결재 대기목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dapproved.ad?page=1\">전자결재 승인목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dreturn.ad?page=1\">전자결재 반려목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/ddefer.ad?page=1\">전자결재 보류목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/flist?page=1\">문서 양식함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">업무일지 작성</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">직원 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">관리자 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/approval/draftWrite.jsp\">기안작성</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dtemp?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">임시보관함</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 대기목록</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/dapproved?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 승인목록</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 반려목록</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/ddefer?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 보류목록</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}  
      out.write("\r\n");
      out.write("<!-- 전자결재 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--관리비 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#maintenance\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-calculator\"></i> <span>관리비관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"maintenance\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bwlist\">일반관리비 목록 </a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/bilist\">고지서(전부) 목록 </a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/maintenance/BillList.jsp\">고지서 상세 목록 조회</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/maintenance/BillListDetailView.jsp\">상세보기</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bvis\">부과기초작업</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/imvas\">연습용</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("<!-- 관리비 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\t");
 if(emp != null && emp.getEmpNo().equals("admin")) { 
      out.write("\r\n");
      out.write("<!--공지사항 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t  \t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#notice\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-bullhorn\"></i> <span>행정관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"notice\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/no.list\">공지사항 관리</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"*\">민원 관리 </a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/vo.list\">주민투표 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"*\">자유게시판 관리</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("<!--공지사항 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--캘린더 시작 -->\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("        <!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("         <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("            href=\"/hiapt/views/common/schedule/schedulemain.jsp\"> <i\r\n");
      out.write("               class=\"fas fa-fw fa-calendar-alt\"></i> <span>Calendar</span></a>\r\n");
      out.write("         </li>\r\n");
      out.write("<!--캘린더 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("\t\t\t<div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("\t\t\t\t<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("<!-- 왼쪽 메인 메뉴 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 끝  --> \r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("<!--- 중앙 전체 큰 틀 ---------------------------------------------->\r\n");
      out.write("<!-- Content Wrapper -->\r\n");
      out.write("<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!---탑메뉴  시작 =================---------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!---탑 메뉴  시작 =================---------------------------->\r\n");
      out.write("\t\t\t\t<nav\r\n");
      out.write("\t\t\t\t\tclass=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t\t\t\t\t<button id=\"sidebarToggleTop\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t<!-- Topbar Navbar -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\t\t\t\t\t\t\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!--알림 아이콘 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t<!-- Dropdown - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"dropdown-header\">알림</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">2019, 10.20</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t알림 메세지 샘플1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item text-center small text-gray-500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\">알림 더 읽기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("<!--알림 아이콘 끝-->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 채팅 알림창   -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a class=\"nav-link dropdown-toggle\" \r\n");
      out.write("\t\t\t\t\t\thref=\"#\" id=\"messagesDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"window.open('/hiapt/views/emp/chat/chatManager.jsp?empno=");
      out.print( emp.getEmpNo() );
      out.write("','name(채팅)','width=350,height=700')\"\r\n");
      out.write("\t\t\t\t\t\t> <i class=\"fas fa-comment-dots fa-fw\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 개인정보 창  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
      out.print( emp.getEmpName() );
      out.write("</span> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-profile rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/hiapt/resources/images/avatar.png\">\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - User Information -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"userDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hiapt/eout\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("<!-- 개인정보 창 끝  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("<!--========================================================================================== -->");
      out.write("\r\n");
      out.write("<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Begin Page Content -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- 본문 타이틀 들어가는 부분 ---->\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("<!--///////본문 내용 시작 ///////-------->\t\r\n");
      out.write("<h1 class=\"h3 mb-4 text-gray-800\">Schedule</h1>\r\n");
      out.write("<div class=\"card shadow mb-4\">\r\n");
      out.write("<div class=\"card-body\">\t\r\n");
      out.write("<table class=\"table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"left\"colspan=\"2\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary btn-sm\"><a href=\"schedulemain.jsp?year=");
out.print(year-1);
      out.write("&month=");
out.print(month);
      out.write("\"><span class=\"text-white\">◀</span></a></button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary btn-sm\"><a href=\"schedulemain.jsp?year=");
out.print(year+1);
      out.write("&month=");
out.print(month);
      out.write("\"><span class=\"text-white\">▶</span></a></button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align=\"center\"colspan=\"3\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary btn-sm\"><a href=\"schedulemain.jsp?year=");
out.print(year);
      out.write("&month=");
out.print(month-1);
      out.write("\"><span class=\"text-white\">◁</span></a></button>\r\n");
      out.write("\t\t\t<span style=\"font-size:20pt;\">");
 out.print(year); 
      out.write('년');
 out.print(month+1); 
      out.write("월</span>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary btn-sm\"><a href=\"schedulemain.jsp?year=");
out.print(year);
      out.write("&month=");
out.print(month+1);
      out.write("\"><span class=\"text-white\">▷</span></a></button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align=right colspan=\"2\"><button class=\"btn btn-sm btn-outline-primary shadow-sm\" id=\"schin\" >\r\n");
      out.write("\t\t\t오늘 날짜</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("  \t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t<thead class=\"thead-dark\">\r\n");
      out.write("   \t\t<tr class=\"text-center\">\r\n");
      out.write("     \t\t<th scope=\"col\" style=\"width:13.5%\">일</th><!-- 일=1 -->\r\n");
      out.write("      \t\t<th scope=\"col\"style=\"width:14%\">월</th><!-- 월=2 -->\r\n");
      out.write("      \t\t<th scope=\"col\"style=\"width:14%\">화</th><!-- 화=3 -->\r\n");
      out.write("      \t\t<th scope=\"col\"style=\"width:14%\">수</th><!-- 수=4 -->\r\n");
      out.write("      \t\t<th scope=\"col\"style=\"width:14%\">목</th><!-- 목=5 -->\r\n");
      out.write("      \t\t<th scope=\"col\"style=\"width:14%\">금</th><!-- 금=6 -->\r\n");
      out.write("      \t\t<th scope=\"col\" style=\"width:13.5%\">토</th><!-- 토=7 -->\r\n");
      out.write("    \t</tr> \r\n");
      out.write("  \t\t</thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("\t\t<tr class=\"intable\">\r\n");
      out.write("\t\t");

			int br = 0;
			for(int i = 0; i < (start-1); i++){
				out.println("<td>&nbsp;</td>");
				br++;
				if((br % 7) == 0){
					out.println("<br>");
				}
			}
			
			for(int i = 1; i <= lastday; i++){
				
				if(year == cy && month == cm&& i==cd){
					
					out.println("<td style='z-index:100; background:#FCF8E3;' id='"+i+"'>"+i+"</td>");
				}else{
					out.println("<td style='z-index:100;' id='"+i+"'>"+i+"</td>");
				}
				br++;
				
				if((br%7) == 0 && i != lastday){
					out.println("</tr><tr class='intable'>");
				}
			}
			while((br++) % 7 != 0){
				out.println("<td>&nbsp;</td>");
			}			
			
		
      out.write("\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"test\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div><!-- /.container-fluid -->\t\t\t\t\r\n");
      out.write("</div><!-- End of Main Content -->\t\r\n");
      out.write("<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("<!-- Footer ìì -->\r\n");
      out.write("\t\t\t<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t\t\t\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t\t\t\t<span>Copyright &copy; HIAPT Website 2019</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("<!-- Footer ë -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("</div>\t<!-- End of Content Wrapper -->\r\n");
      out.write("</div>\t<!-- End of Page Wrapper -->\t\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- top 버튼 -->\r\n");
      out.write("<!-- top ë²í¼ -->\r\n");
      out.write("\t<!-- Scroll to Top Button-->\r\n");
      out.write("\t<a class=\"scroll-to-top rounded\" href=\"#page-top\"> \r\n");
      out.write("\t<i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/sb-admin-2.min.js\"></script>");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
