/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-05 08:49:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.emp.approval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import oracle.net.aso.k;
import draft.model.vo.Draft;
import java.util.ArrayList;
import employee.model.vo.Employee;

public final class returnDoc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/emp/approval/../../common/empnavi.jsp", Long.valueOf(1572943015756L));
    _jspx_dependants.put("/views/emp/approval/../../common/empTopNavi.jsp", Long.valueOf(1572942522928L));
    _jspx_dependants.put("/views/emp/approval/../../common/empfooter.html", Long.valueOf(1571394836959L));
    _jspx_dependants.put("/views/emp/approval/../../common/topbutton.html", Long.valueOf(1571652039501L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("draft.model.vo.Draft");
    _jspx_imports_classes.add("oracle.net.aso.k");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("employee.model.vo.Employee");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Draft> list = (ArrayList<Draft>) request.getAttribute("list");
	int currentPage = ((Integer) request.getAttribute("currentPage")).intValue();
	int beginPage = ((Integer) request.getAttribute("beginPage")).intValue();
	int endPage = ((Integer) request.getAttribute("endPage")).intValue();
	int maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
	int count = ((Integer) request.getAttribute("count")).intValue();
	String keyword = (String) request.getAttribute("keyword");
	String search = (String) request.getAttribute("search");
	String begin = (String) request.getAttribute("begin");
	String to = (String) request.getAttribute("to");
	String empno = (String) request.getAttribute("empno");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>HIAPTProject</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom fonts for this template-->\r\n");
      out.write("\t<link href=\"/hiapt/resources/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\t<!-- Custom styles for this template-->\r\n");
      out.write("\t<link href=\"/hiapt/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/hiapt/resources/css/basic.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page level plugins -->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--// css or jQuery or javaScript 삽입 부분    -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 시작 --> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Employee emp = (Employee)session.getAttribute("employee");

      out.write("\r\n");
      out.write("<!-- 메일관련 요소 -->\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".contextmenu {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background: #FFFFFF;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  box-shadow:\r\n");
      out.write("    0 15px 35px rgba(50,50,90,0.1),\r\n");
      out.write("    0 5px 15px rgba(0,0,0,0.07);\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  z-index: 999999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/hiapt/mbtlist\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tdata : {empemail : $(\"#empemail\").val()},\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar values = \"\";\r\n");
      out.write("\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\tvalues += \"<a href='/hiapt/mymb?mcode=\"+json.list[i].mcode+\"&email=\"+json.list[i].email+\"&name=\"\r\n");
      out.write("\t\t\t\t\t\t+decodeURIComponent(json.list[i].name).replace(/\\+/gi, \" \")+\"' class='q'>\"\r\n");
      out.write("\t\t\t\t\t\t+ decodeURIComponent(json.list[i].name).replace(/\\+/gi, \" \") + \"</a><br>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjson.list[i].email\r\n");
      out.write("\t\t\t$(\"#a\").html($(\"#a\").html() + values);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#send\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\turl : \"/hiapt/mtenroll\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tdata : { mbox : $(\"#boxname\").val(),\r\n");
      out.write("\t\t\t\t empemail : $(\"#empemail\").val()\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t$(\"#a\").html($(\"#a\").html() \r\n");
      out.write("\t\t+ \"<a href='/hiapt/mymb?mcode=\"+data.mcode+\"&email=\"+data.email+\"&name=\"\r\n");
      out.write("\t\t\t+decodeURIComponent(data.name).replace(/\\+/gi, \" \")+\"' class='q'>\"\r\n");
      out.write("\t\t\t+ decodeURIComponent(data.name).replace(/\\+/gi, \" \") + \"</a><br>\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<input type=\"hidden\" id=\"empemail\" value=\"");
      out.print( emp.getEmpEmail() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"contextmenu\">\r\n");
      out.write("  <li><a href=\"#\">Simple link</a></li>\r\n");
      out.write("  <li><a href=\"#\">Link to somewhere</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 시작  --> \r\n");
      out.write("\t\t<ul\r\n");
      out.write("\t\t\tclass=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("\t\t\tid=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("<!-- 스마일 로고 -->\r\n");
      out.write("\t\t\t<a class=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("\t\t\t\thref=\"/hiapt/login.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("\t\t\t\t\tHIAPT <sup>2</sup>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("<!-- 왼쪽 메뉴바 시작 -->\r\n");
      out.write("<!-- ============================================================= -->\t\t\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 메일 시작 -->\r\n");
      out.write("\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\tdata-toggle=\"collapse\" data-target=\"#mail\" aria-expanded=\"true\"\r\n");
      out.write("\t\taria-controls=\"collapseTwo\"> <i class=\"fas fa-fw fa-envelope-open\"></i>\r\n");
      out.write("\t\t\t<span>메일</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t\t<div id=\"mail\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("\t\t\tdata-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emlist\">메일쓰기</a>\r\n");
      out.write("\t\t\t\t<!-- \"/hiapt/views/emp/mail/writemail.jsp\" -->\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/views/emp/mail/selfwritemail.jsp\">내게쓰기</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=0\">전체메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=1\">받은메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=2\">보낸메일함</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=3\">임시보관함</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=4\">내게 쓴\r\n");
      out.write("\t\t\t\t\t메일함</a> <a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=5\">휴지통</a>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div class=\"dropdown\" style=\"display:inline-block;\">\r\n");
      out.write("  \t\t\t\t\t\t\t&nbsp;<button class=\"btn btn-link btn-sm dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\">\r\n");
      out.write("  \t\t\t\t\t\t\t</button><span>내 메일함</span>&nbsp;\r\n");
      out.write("  \t\t\t\t\t\t\t<div id=\"a\" class=\"dropdown-menu\">  \t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <button id=\"insert\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></button> -->\r\n");
      out.write("\t\t\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-plus fa-fw fa-envelope-open\"></i>  \r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" style=\"display:inline-block;\">내 메일함</a>&nbsp;<a href=\"#\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메일 끝 -->\r\n");
      out.write("<!-- ====================================================================================== -->\r\n");
      out.write("<!-- ====================================================================================== -->\t\t\t\r\n");
      out.write("<!--인사정보 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t      \t\r\n");
      out.write("\t\t\t");
 if(emp != null && emp.getEmpId().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/employee/empEnroll.jsp\">직원등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/empdetail?empno=");
      out.print( emp.getEmpNo() );
      out.write("\">내정보보기</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/user/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- 인사정보 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--전자결재 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t\t");
 if(emp != null && emp.getEmpNo().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist.ad?page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby.ad?page=1\">전자결재 대기목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dapproved.ad?page=1\">전자결재 승인목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dreturn.ad?page=1\">전자결재 반려목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/flist?page=1\">문서 양식함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">업무일지 작성</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">직원 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">관리자 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/approval/draftWrite.jsp\">기안작성</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dtemp?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">임시보관함</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 대기목록</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/dapproved?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 승인목록</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 반려목록</a> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}  
      out.write("\r\n");
      out.write("<!-- 전자결재 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--관리비 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#maintenance\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-calculator\"></i> <span>관리비관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"maintenance\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bwlist\">일반관리비 목록 </a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/bilist\">고지서(전부) 목록 </a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/maintenance/BillList.jsp\">고지서 상세 목록 조회</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/views/emp/maintenance/BillListDetailView.jsp\">상세보기</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bvis\">부과기초작업</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"/hiapt/imvas\">연습용</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("<!-- 관리비 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--공지사항 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t  \t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#notice\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-bullhorn\"></i> <span>행정관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"notice\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/no.list\">공지사항 관리</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/co.list\">민원 관리 </a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/vo.list\">주민투표 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"*\">자유게시판 관리</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\r\n");
      out.write("<!--공지사항 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--캘린더 시작 -->\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("        <!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("         <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("            href=\"/hiapt/views/common/schedule/schedulemain.jsp\"> <i\r\n");
      out.write("               class=\"fas fa-fw fa-calendar-alt\"></i> <span>Calendar</span></a>\r\n");
      out.write("         </li>\r\n");
      out.write("<!--캘린더 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("\t\t\t<div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("\t\t\t\t<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("<!-- 왼쪽 메인 메뉴 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 끝  --> \r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("<!--- 중앙 전체 큰 틀 ---------------------------------------------->\r\n");
      out.write("<!-- Content Wrapper -->\r\n");
      out.write("<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!---탑메뉴  시작 =================---------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t    url : \"/hiapt/ncount\",\r\n");
      out.write("\t    type : \"post\",\r\n");
      out.write("\t    dataType : \"text\",\r\n");
      out.write("\t    success : function(data) {\r\n");
      out.write("\t    \tconsole.log(\"data : \" + data);\r\n");
      out.write("\t    \tif(data > 0){\r\n");
      out.write("\t    \t\t$(\"#approval\").html(\"결재할 문서 : \" + data + \"개\");\r\n");
      out.write("\t        }else {\r\n");
      out.write("\t        \t$(\"#approval\").html(\"결재할 문서가 없습니다.\");\r\n");
      out.write("\t        }\t\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t        error : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + textStatus + errorThrown + jqXHR);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t  \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!---탑 메뉴  시작 =================---------------------------->\r\n");
      out.write("\t\t\t\t<nav\r\n");
      out.write("\t\t\t\t\tclass=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t\t\t\t\t<button id=\"sidebarToggleTop\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t<!-- Topbar Navbar -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\t\t\t\t\t\t\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!--알림 아이콘 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t<!-- Dropdown - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"dropdown-header\">알림</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-800\">전자결재 알림</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"approval\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("<!--알림 아이콘 끝-->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 채팅 알림창   -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a class=\"nav-link dropdown-toggle\" \r\n");
      out.write("\t\t\t\t\t\thref=\"#\" id=\"messagesDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"window.open('/hiapt/views/emp/chat/chatManager.jsp?empno=");
      out.print( emp.getEmpNo() );
      out.write("','name(채팅)','width=350,height=700')\"\r\n");
      out.write("\t\t\t\t\t\t> <i class=\"fas fa-comment-dots fa-fw\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 개인정보 창  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
      out.print( emp.getEmpName() );
      out.write("</span> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-profile rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/hiapt/resources/images/avatar.png\">\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - User Information -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"userDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hiapt/eout\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("<!-- 개인정보 창 끝  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("<!--========================================================================================== -->");
      out.write("\r\n");
      out.write("<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Begin Page Content -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
 if(emp.getEmpNo().equals(empno)) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--///////본문 내용 시작 ///////-------->\r\n");
      out.write("<div style=\"float: right; display: flex;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<select id=\"searchselect\" name=\"searchselect\"\r\n");
      out.write("\t\t\tstyle=\"width: 100px; padding-left: 5px;\"\r\n");
      out.write("\t\t\tclass=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t<option selected=\"selected\">제목</option>\r\n");
      out.write("\t\t\t<option id=\"opt2\">작성자</option>\r\n");
      out.write("\t\t\t<option id=\"opt3\">날짜</option>\r\n");
      out.write("\t\t\t<option id=\"opt4\">문서형식</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"title\">\r\n");
      out.write("\t\t<form action=\"/hiapt/dsearchr\" method=\"get\" id=\"searchform\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"empno\" value=\"");
      out.print(emp.getEmpNo());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"search\" value=\"title\">\r\n");
      out.write("\t\t\t<div class=\"input-group\" style=\"margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"search\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control form-control-sm\" placeholder=\"검색할 제목을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" type=\"button\" id=\"submitbtn\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"writer\">\r\n");
      out.write("\t\t<form action=\"/hiapt/dsearchr\" method=\"get\" id=\"searchform2\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"empno\" value=\"");
      out.print(emp.getEmpNo());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"search\" value=\"writer\">\r\n");
      out.write("\t\t\t<div class=\"input-group\" style=\"margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"search\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control form-control-sm\" placeholder=\"검색할 작성자를 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tid=\"submitbtn2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"date\">\r\n");
      out.write("\t\t<form action=\"/hiapt/dsearchr\" method=\"get\" id=\"searchform3\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"empno\" value=\"");
      out.print(emp.getEmpNo());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"search\" value=\"date\">\r\n");
      out.write("\t\t\t<div class=\"input-group\" style=\"margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"from\" id=\"search\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 140px; border-radius: 3px;\"> &nbsp; ～ &nbsp;<input\r\n");
      out.write("\t\t\t\t\ttype=\"date\" name=\"to\" id=\"search\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 140px; border-radius: 3px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tid=\"submitbtn3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"formtype\">\r\n");
      out.write("\t\t<form action=\"/hiapt/dsearchr\" method=\"get\" id=\"searchform4\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"empno\" value=\"");
      out.print(emp.getEmpNo());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"search\" value=\"formtype\">\r\n");
      out.write("\t\t\t<div class=\"input-group\" style=\"margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"search\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control form-control-sm\" placeholder=\"검색할 문서형식을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tid=\"submitbtn4\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<div style=\"display: flex;\">\r\n");
      out.write("\t\t<div style=\"color: #444;\">\r\n");
      out.write("\t\t［반려 문서 : ");
      out.print(count);
      out.write("개］\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
 if(keyword != null) { 
      out.write("\r\n");
      out.write("\t<div align=\"center\" style=\"color: #644b90; font-size: 11pt; font-weight: bold;\">\r\n");
      out.write("\t\t［검색어 : ");
      out.print( keyword );
      out.write("］\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 } else if (begin != null && to != null) { 
      out.write("\r\n");
      out.write("\t<div  align=\"center\" style=\"color: #644b90; font-size: 11pt; font-weight: bold;\">\r\n");
      out.write("\t\t［검색 날짜 : ");
      out.print( begin );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print( to );
      out.write("］\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 } 
      out.write("<br>\r\n");
      out.write("\t<div class=\"card shadow mb-4\">\r\n");
      out.write("\t\t<div class=\"card-body\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table beauty-table table-hover\"\r\n");
      out.write("\t\t\t\tstyle=\"text-align: center; \">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"10\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"check\">\r\n");
      out.write("       \t\t\t\t\t     <input type=\"checkbox\" id=\"checkall\">\r\n");
      out.write("         \t\t\t\t\t <span class=\"checkmark\"></span>\r\n");
      out.write("          \t\t\t\t \t </label>\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"80\">첨부파일</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"100\">문서번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"125\">기안자</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"100\">기안일</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"120\">문서종류</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"80\">진행상태</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					for (int i = 0; i < list.size(); i++) {
						Draft d = list.get(i);
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"check\">\r\n");
      out.write("       \t\t\t\t    <input type=\"checkbox\">\r\n");
      out.write("       \t\t\t\t\t<span class=\"checkmark\"></span>\r\n");
      out.write("        \t\t\t    </label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
 if(d.getOriginfile() != null && !d.getOriginfile().equals("null")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-paperclip\"></i>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(d.getDocno());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"/hiapt/dview?empno=");
      out.print( emp.getEmpNo() );
      out.write("&docno=");
      out.print(d.getDocno());
      out.write('"');
      out.write('>');
      out.print(d.getDoctitle());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(d.getEmpid());
      out.write("&nbsp;");
      out.print(d.getEmpname());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(d.getDraftdate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(d.getFormname());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if (d.getDocstatus().equals("0")) {
							
      out.write(" 대기중 ");

								} else if (d.getDocstatus().equals("1")) {
							
      out.write(" 진행중 ");

								} else if (d.getDocstatus().equals("2")) {
							
      out.write(" 결재완료 ");

								} else if (d.getDocstatus().equals("3")) {
							
      out.write(" 반려됨 ");

								} else if (d.getDocstatus().equals("3")) { 
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t 보류중\r\n");
      out.write("\t\t\t\t\t\t\t ");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div style=\"float: right;\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"이동\" class=\"btn btn-default btn-xs\"\r\n");
      out.write("\t\t\t\t\tstyle=\"letter-spacing: 7px; padding-left: 10px;\">\r\n");
      out.write("\t\t\t</div>\r\n");
if(keyword == null) { 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t<div class=\"paging_simple_numbers\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if ((beginPage - 10) < 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							for (int p = beginPage; p <= endPage; p++) {
								if (p == currentPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page");
      out.print(p);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=");
      out.print(p);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if ((endPage + 10) > maxPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t<div class=\"paging_simple_numbers\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if ((beginPage - 10) < 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dataTable_previous\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							for (int p = beginPage; p <= endPage; p++) {
								if (p == currentPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item active next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=");
      out.print(p);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=");
      out.print(p);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if ((endPage + 10) > maxPage) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/hiapt/dsearchr?empno=");
      out.print( emp.getEmpNo() );
      out.write("&search=");
      out.print(search );
      out.write("&keyword=");
      out.print( keyword);
      out.write("&page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t<div style=\"font-size: 40pt; color: #b31\" align=\"center\" ><br> 해당 목록에 대한 접근 권한이 없습니다. </div>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\"#checkall\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#checkall\").prop(\"checked\")) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"input[type=checkbox]\").prop(\"checked\", true);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"input[type=checkbox]\").prop(\"checked\", false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tshowDiv();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"select[name=searchselect]\").on(\"change\", function() {\r\n");
      out.write("\t\t\tshowDiv();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction showDiv() {\r\n");
      out.write("\t\tif ($(\"#searchselect option:eq(0)\").is(\":selected\")) {\r\n");
      out.write("\t\t\t$(\"#title\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#writer\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#date\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#formtype\").css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif ($(\"#searchselect option:eq(1)\").is(\":selected\")) {\r\n");
      out.write("\t\t\t$(\"#title\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#writer\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#date\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#formtype\").css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif ($(\"#searchselect option:eq(2)\").is(\":selected\")) {\r\n");
      out.write("\t\t\t$(\"#title\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#writer\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#date\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#formtype\").css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif ($(\"#searchselect option:eq(3)\").is(\":selected\")) {\r\n");
      out.write("\t\t\t$(\"#title\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#writer\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#date\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\"#formtype\").css(\"display\", \"block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t  $(\"#submitbtn\").click(function(){\r\n");
      out.write("\t\t        $(\"#searchform\").submit();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t  $(\"#submitbtn2\").click(function(){\r\n");
      out.write("\t\t        $(\"#searchform2\").submit();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t  $(\"#submitbtn3\").click(function(){\r\n");
      out.write("\t\t        $(\"#searchform3\").submit();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t  $(\"#submitbtn4\").click(function(){\r\n");
      out.write("\t\t        $(\"#searchform4\").submit();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t  \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("</div><!-- /.container-fluid -->\t\t\t\t\r\n");
      out.write("</div><!-- End of Main Content -->\t\r\n");
      out.write("<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("<!-- Footer ìì -->\r\n");
      out.write("\t\t\t<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t\t\t\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t\t\t\t<span>Copyright &copy; HIAPT Website 2019</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("<!-- Footer ë -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer 시작 -->\r\n");
      out.write("</div>\t<!-- End of Content Wrapper -->\r\n");
      out.write("</div>\t<!-- End of Page Wrapper -->\t\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- top 버튼 -->\r\n");
      out.write("<!-- top ë²í¼ -->\r\n");
      out.write("\t<!-- Scroll to Top Button-->\r\n");
      out.write("\t<a class=\"scroll-to-top rounded\" href=\"#page-top\"> \r\n");
      out.write("\t<i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/sb-admin-2.min.js\"></script>");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
