/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-05 10:34:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.emp.maintenance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import maintenance.model.vo.BaseView;
import java.util.ArrayList;
import employee.model.vo.Employee;

public final class baseViewList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/emp/maintenance/../../common/empfooter.html", Long.valueOf(1571394836959L));
    _jspx_dependants.put("/views/emp/maintenance/../../common/topbutton.html", Long.valueOf(1571652039501L));
    _jspx_dependants.put("/views/emp/maintenance/../../common/empTopNavi.jsp", Long.valueOf(1572942522928L));
    _jspx_dependants.put("/views/emp/maintenance/../../common/empnavi.jsp", Long.valueOf(1572947987524L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("maintenance.model.vo.BaseView");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("employee.model.vo.Employee");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<BaseView> list = (ArrayList<BaseView>) request.getAttribute("list");
	//BaseView bview = (BaseView)request.getAttribute("bview");
	int currentPage = (Integer) request.getAttribute("currentPage");
	int beginPage = (Integer) request.getAttribute("beginPage");
	int endPage = (Integer) request.getAttribute("endPage");
	int maxPage = (Integer) request.getAttribute("maxPage");
	String months = (String)request.getAttribute("months");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- head 시작 -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>HIAPTProject</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom fonts for this template-->\r\n");
      out.write("\t<link href=\"/hiapt/resources/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!-- Custom styles for this template-->\r\n");
      out.write("\t<link href=\"/hiapt/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/hiapt/resources/css/basic.css\" rel=\"stylesheet\">\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--// css or jQuery or javaScript 삽입 부분    -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function callFunction(){\r\n");
      out.write("\t window.location.href =\"/hiapt/views/emp/maintenance/BillViewInsertForm.jsp\";\r\n");
      out.write("\t return false; // 다른 이벤트 전달 막기\r\n");
      out.write(" }\r\n");
      out.write(" function callFunction4(){\r\n");
      out.write("\t window.location.href =\"/hiapt/views/emp/maintenance/baseViewInsertForm_addRow.jsp\";\r\n");
      out.write("\t return false; // 다른 이벤트 전달 막기\r\n");
      out.write(" } \r\n");
      out.write(" // 체크박스 전체선택\r\n");
      out.write(" function checkAll(){\r\n");
      out.write("       if( $(\"#th_checkAll\").is(':checked') ){\r\n");
      out.write("        $(\"input[name=checkRow]\").prop(\"checked\", true);\r\n");
      out.write("        }else{\r\n");
      out.write("         $(\"input[name=checkRow]\").prop(\"checked\", false);\r\n");
      out.write("       }\r\n");
      out.write(" } \r\n");
      out.write("  \r\n");
      out.write(" // \r\n");
      out.write(" function test_checkbox(){\r\n");
      out.write("\t var flag = false;\r\n");
      out.write("\t // 체크박스 접근 후 체크된 갯수 확인\r\n");
      out.write("\t var values = document.getElementsByName(\"checkRow\");\r\n");
      out.write("\t console.log(values.length);\r\n");
      out.write("\t var count = 0;\r\n");
      out.write("\t var r= null;\r\n");
      out.write("\t for(var i = 0; i<values.length; i++){\r\n");
      out.write("\t\t if(values[i].checked) {\r\n");
      out.write("\t\t\t count++;\r\n");
      out.write("\t\t\t r = values[i].value;\r\n");
      out.write("\t\t\t console.log(\", \" + r + \", \" + typeof(r));\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("\t if(count < 1 ){\r\n");
      out.write("\t\t alert(\"1개 이상 선택해야 합니다.\");\r\n");
      out.write("\t } else if(confirm(\"정말 삭제하시겠습니까?\") == true) {\t\t\r\n");
      out.write("\t\t flag = true;\r\n");
      out.write("\t } else{\r\n");
      out.write("\t\t return flag;\r\n");
      out.write("\t }\r\n");
      out.write("\t return flag;\t\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 왼쪽 메인 메뉴바 시작 -->\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

	Employee emp = (Employee)session.getAttribute("employee");

      out.write("\r\n");
      out.write("<!-- 메일관련 요소 -->\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".contextmenu {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background: #FFFFFF;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  box-shadow:\r\n");
      out.write("    0 15px 35px rgba(50,50,90,0.1),\r\n");
      out.write("    0 5px 15px rgba(0,0,0,0.07);\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  z-index: 999999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/hiapt/mbtlist\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tdata : {empemail : $(\"#empemail\").val()},\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar values = \"\";\r\n");
      out.write("\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\tvalues += \"<a href='/hiapt/mymb?mcode=\"+json.list[i].mcode+\"&email=\"+json.list[i].email+\"&name=\"\r\n");
      out.write("\t\t\t\t\t\t+decodeURIComponent(json.list[i].name).replace(/\\+/gi, \" \")+\"' class='q'>\"\r\n");
      out.write("\t\t\t\t\t\t+ decodeURIComponent(json.list[i].name).replace(/\\+/gi, \" \") + \"</a><br>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjson.list[i].email\r\n");
      out.write("\t\t\t$(\"#a\").html($(\"#a\").html() + values);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#send\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\turl : \"/hiapt/mtenroll\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tdata : { mbox : $(\"#boxname\").val(),\r\n");
      out.write("\t\t\t\t empemail : $(\"#empemail\").val()\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t$(\"#a\").html($(\"#a\").html() \r\n");
      out.write("\t\t+ \"<a href='/hiapt/mymb?mcode=\"+data.mcode+\"&email=\"+data.email+\"&name=\"\r\n");
      out.write("\t\t\t+decodeURIComponent(data.name).replace(/\\+/gi, \" \")+\"' class='q'>\"\r\n");
      out.write("\t\t\t+ decodeURIComponent(data.name).replace(/\\+/gi, \" \") + \"</a><br>\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<input type=\"hidden\" id=\"empemail\" value=\"");
      out.print( emp.getEmpEmail() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"contextmenu\">\r\n");
      out.write("  <li><a href=\"#\">Simple link</a></li>\r\n");
      out.write("  <li><a href=\"#\">Link to somewhere</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 왼쪽 메인 메뉴바 시작  --> \r\n");
      out.write("\t\t<ul\r\n");
      out.write("\t\t\tclass=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("\t\t\tid=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("<!-- 스마일 로고 -->\r\n");
      out.write("\t\t\t<a class=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("\t\t\t\thref=\"/hiapt/index.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("\t\t\t\t\tHIAPT <sup>2</sup>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("<!-- 왼쪽 메뉴바 시작 -->\r\n");
      out.write("<!-- ============================================================= -->\t\t\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ============================================================= -->\r\n");
      out.write("<!-- 메일 시작 -->\r\n");
      out.write("\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\tdata-toggle=\"collapse\" data-target=\"#mail\" aria-expanded=\"true\"\r\n");
      out.write("\t\taria-controls=\"collapseTwo\"> <i class=\"fas fa-fw fa-envelope-open\"></i>\r\n");
      out.write("\t\t\t<span>메일</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t\t<div id=\"mail\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("\t\t\tdata-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emlist\">메일쓰기</a>\r\n");
      out.write("\t\t\t\t<!-- \"/hiapt/views/emp/mail/writemail.jsp\" -->\r\n");
      out.write("\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/views/emp/mail/selfwritemail.jsp\">내게쓰기</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=0\">전체메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=1\">받은메일함</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=2\">보낸메일함</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=3\">임시보관함</a><a\r\n");
      out.write("\t\t\t\t\tclass=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=4\">내게 쓴\r\n");
      out.write("\t\t\t\t\t메일함</a> <a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\thref=\"/hiapt/mlist?empemail=");
      out.print(emp.getEmpEmail());
      out.write("&mcode=5\">휴지통</a>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div class=\"dropdown\" style=\"display:inline-block;\">\r\n");
      out.write("  \t\t\t\t\t\t\t&nbsp;<button class=\"btn btn-link btn-sm dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\">\r\n");
      out.write("  \t\t\t\t\t\t\t</button><span>내 메일함</span>&nbsp;\r\n");
      out.write("  \t\t\t\t\t\t\t<div id=\"a\" class=\"dropdown-menu\">  \t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <button id=\"insert\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></button> -->\r\n");
      out.write("\t\t\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-plus fa-fw fa-envelope-open\"></i>  \r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" style=\"display:inline-block;\">내 메일함</a>&nbsp;<a href=\"#\"><i class=\"fas fa-plus fa-fw fa-envelope-open\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메일 끝 -->\r\n");
      out.write("<!-- ====================================================================================== -->\r\n");
      out.write("<!-- ====================================================================================== -->\t\t\t\r\n");
      out.write("<!--인사정보 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t      \t\r\n");
      out.write("\t\t\t");
 if(emp != null && emp.getEmpId().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/employee/empEnroll.jsp\">직원등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#employee\" \r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> \r\n");
      out.write("\t\t\t\t<i class=\"fas fa-fw fa-address-card\"></i> \r\n");
      out.write("\t\t\t\t<span>인사</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"employee\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/empdetail?empno=");
      out.print( emp.getEmpNo() );
      out.write("\">내정보보기</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/emplist\">직원조회</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/user/apt/aptEnroll.jsp\">입주자등록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/aptlist\">입주자조회</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- 인사정보 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--전자결재 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t \t\t\t");
 if(emp != null && emp.getEmpNo().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist.ad?page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby.ad?page=1\">전자결재 대기목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dapproved.ad?page=1\">전자결재 완료목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dreturn.ad?page=1\">전자결재 반려목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/flist?page=1\">문서 양식함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"\">업무일지 작성</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/llist.emp?page=1\">직원 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/llist.ad?page=1\">관리자 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#draft\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\taria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>전자결재</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"draft\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/hiapt/dwrite\">기안작성</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dtemp?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">임시보관함</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dlist?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 전체목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dstandby?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 대기목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t <a class=\"collapse-item\" href=\"/hiapt/dapproved?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 완료목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/dreturn?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">전자결재 반려목록</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/llist.my?empno=");
      out.print( emp.getEmpNo() );
      out.write("&page=1\">내 업무일지함</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/mlist.emp?empno=");
      out.print( emp.getEmpNo() );
      out.write("\">내 문서함 목록</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}  
      out.write("\r\n");
      out.write("<!-- 전자결재 끝 --> \t\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--관리비 시작 -->\r\n");
 if(emp != null && !(emp.getEmpNo().equals("admin"))) { 
      out.write("\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t\t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ====================================================================================== -->\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#maintenance\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-calculator\"></i> <span>관리비관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"maintenance\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bvis\">부과기초작업</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/bwlist\">고지서목록 </a>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/*\">수납목록</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/maintenance/baseViewInsertForm_addRow.jsp\">부과기초작업연습용</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/views/emp/maintenance/sms.jsp\">sms연습용</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("<!-- 관리비 끝 -->\r\n");
 } 
      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--공지사항 시작 -->\r\n");
      out.write("\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\t  \t<!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#notice\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-bullhorn\"></i> <span>행정관리</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"notice\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/no.list\">공지사항 관리</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/co.list\">민원 관리 </a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"/hiapt/vo.list\">주민투표 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"*\">자유게시판 관리</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\r\n");
      out.write("<!--공지사항 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!--캘린더 시작 -->\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("        <!-- Heading 나중에 삭제부분-->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("         <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("            href=\"/hiapt/views/common/schedule/schedulemain.jsp\"> <i\r\n");
      out.write("               class=\"fas fa-fw fa-calendar-alt\"></i> <span>Calendar</span></a>\r\n");
      out.write("         </li>\r\n");
      out.write("<!--캘린더 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("\t\t\t<div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("\t\t\t\t<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("<!-- 왼쪽 메인 메뉴 끝 -->\r\n");
      out.write("<!-- ================================================================================= -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 왼쪽 메인 메뉴바 끝  -->\r\n");
      out.write("\t\t<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--- 중앙 전체 큰 틀 ---------------------------------------------->\r\n");
      out.write("\t\t<!-- Content Wrapper -->\r\n");
      out.write("\t\t<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\t\t\t<!-- Main Content -->\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ================================================================================= -->\r\n");
      out.write("\t\t\t\t<!---탑메뉴  시작 =================---------------------------->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t    url : \"/hiapt/ncount\",\r\n");
      out.write("\t    type : \"post\",\r\n");
      out.write("\t    dataType : \"text\",\r\n");
      out.write("\t    success : function(data) {\r\n");
      out.write("\t    \tconsole.log(\"data : \" + data);\r\n");
      out.write("\t    \tif(data > 0){\r\n");
      out.write("\t    \t\t$(\"#approval\").html(\"결재할 문서 : \" + data + \"개\");\r\n");
      out.write("\t        }else {\r\n");
      out.write("\t        \t$(\"#approval\").html(\"결재할 문서가 없습니다.\");\r\n");
      out.write("\t        }\t\r\n");
      out.write("\t    \t},\r\n");
      out.write("\t        error : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + textStatus + errorThrown + jqXHR);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t  \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<!---탑 메뉴  시작 =================---------------------------->\r\n");
      out.write("\t\t\t\t<nav\r\n");
      out.write("\t\t\t\t\tclass=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t\t\t\t\t<button id=\"sidebarToggleTop\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t<!-- Topbar Navbar -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\t\t\t\t\t\t\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!--알림 아이콘 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t<!-- Dropdown - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"dropdown-header\">알림</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-800\">전자결재 알림</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"approval\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("<!--알림 아이콘 끝-->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 채팅 알림창   -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a class=\"nav-link dropdown-toggle\" \r\n");
      out.write("\t\t\t\t\t\thref=\"#\" id=\"messagesDropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"window.open('/hiapt/views/emp/chat/chatManager.jsp?empno=");
      out.print( emp.getEmpNo() );
      out.write("','name(채팅)','width=350,height=700')\"\r\n");
      out.write("\t\t\t\t\t\t> <i class=\"fas fa-comment-dots fa-fw\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- 개인정보 창  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
      out.print( emp.getEmpName() );
      out.write("</span> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-profile rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/hiapt/resources/images/avatar.png\">\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - User Information -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"userDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hiapt/eout\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("<!-- 개인정보 창 끝  -->\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("<!--========================================================================================== -->");
      out.write("\r\n");
      out.write("\t\t\t\t<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("\t\t\t\t<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t<!-- Begin Page Content -->\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--///////본문 내용 시작 ///////-------->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 본문 타이틀 들어가는 부분 ---->\r\n");
      out.write("\t\t\t\t\t<h1 class=\"h3 mb-4 text-gray-800\">부과기초작업</h1>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!--///////본문 내용 시작 ///////-------->\r\n");
      out.write("\t\t\t\t\t<div class=\"card shadow mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("              \r\n");
      out.write("\t\t\t\t\t\t\t<!-- 부과년월 검색 -->\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"/hiapt/bvis\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"search\" value=\"months\"/> <label>부과년월&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"month\" name=\"months\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"검색\" onclick=\"sendIt()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-title\" style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button onclick=\"callFunction4();\" class=\"btn btn-sm btn-info shadow-sm\" >부과기초작업등록</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<button onclick=\"callFunction();\" class=\"btn btn-sm btn-warning shadow-sm\" >관리비등록</button>&nbsp;<!-- \r\n");
      out.write("\t\t\t\t\t\t\t<button onclick=\"callFunction2();\" class=\"btn btn-sm btn-success shadow-sm\" >엑셀자료올리기</button>&nbsp; -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"/hiapt/bvidel\" name=\"form\" onsubmit=\"return test_checkbox();\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-title\" style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn btn-sm btn-outline-primary shadow-sm\" type=\"submit\" value=\"삭제\"> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("                \t\t\t<table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <th rowspan=\"2\">삭제\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>삭제</th>\t\t \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">상태</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">고지서번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">부과년월</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th colspan=\"2\">산출기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">납부마감일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">부과마감일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">마감횟수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th rowspan=\"2\">출력의뢰일시</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"check\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("  \t\t\t\t\t\t\t\tid=\"th_checkAll\" onclick=\"checkAll();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"checkmark center-block\" ></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>시작일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>종료일</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for (BaseView ba : list) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr name=\"trImpose\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"check\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" name=\"checkRow\" value=\"");
      out.print(ba.getMerchantUid() );
      out.write("\" \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\tid=\"customCheck\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"checkmark\" ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getImposeStatus());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"/hiapt/bidv?merchantUid=");
      out.print( ba.getMerchantUid() );
      out.write('"');
      out.write('>');
      out.print(ba.getMerchantUid() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getBillYearMonth());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getCalculateStartDay());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getCalculateEndDay());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getCutoffDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getImposeEndDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getImposeCount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(ba.getCutoffDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t<!-- pageing -->\r\n");
      out.write("\r\n");
      out.write("\t\t  <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"paging_simple_numbers\">\r\n");
      out.write("\t\t\t");
 if( months != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 if((beginPage - 10) < 1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=");
      out.print( beginPage -10 );
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"");
      out.print( beginPage - 10 );
      out.write("\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t");
 if( (beginPage -10) <= 9){ 
      out.write("\r\n");
      out.write("               \t\t<li class=\"paginate_button page-item active\"\r\n");
      out.write("                  \t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("                 \t \tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">1</a></li>\r\n");
      out.write("              \t \t");
 }else{ 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 for(int p = beginPage; p <= endPage; p++){
						if(p == currentPage){	
					
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item active next\"><a href=\"/hiapt/bvis?page");
      out.print( p );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( p );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( p );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( p );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");
 }} 
      out.write("\r\n");
      out.write("\t\t\t\t\t ");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t\t");
 if((endPage + 10) > maxPage ) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( maxPage );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( maxPage );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page");
      out.print( endPage + 10 );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( endPage + 10 );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( maxPage );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( maxPage );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t</ul>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 if((beginPage - 10) < 1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=1\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"0\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/bvis?page=");
      out.print( beginPage -10 );
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\tdata-dt-idx=\"");
      out.print( beginPage - 10 );
      out.write("\" tabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 for(int p = beginPage; p <= endPage; p++){
						if(p == currentPage){	
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item active next\"><a href=\"/hiapt/bvis?page");
      out.print( p );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( p );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( p );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( p );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t");
 }} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 if((endPage + 10) > maxPage ) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( maxPage );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( maxPage );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page");
      out.print( endPage + 10 );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( endPage + 10 );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/hiapt/bvis?page=");
      out.print( maxPage );
      out.write("\" aria-controls=\"dataTable\" data-dt-idx=\"");
      out.print( maxPage );
      out.write("\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t ");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t<div class=\"card-title\" style=\"float:right;\">\t\t\t\t\t\t          \r\n");
      out.write("\t\t<a href=\"/hiapt/index.jsp\" class=\"btn btn-sm btn-secondary shadow-sm\">HOME</a></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End of Main Content -->\r\n");
      out.write("\t\t\t<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("\t\t\t<!-- footer 시작 -->\r\n");
      out.write("\t\t\t");
      out.write("<!-- Footer ìì -->\r\n");
      out.write("\t\t\t<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t\t\t\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t\t\t\t<span>Copyright &copy; HIAPT Website 2019</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("<!-- Footer ë -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- footer 시작 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End of Content Wrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End of Page Wrapper -->\r\n");
      out.write("\t<!--========================================================================================== -->\r\n");
      out.write("\t<!-- top 버튼 -->\r\n");
      out.write("\t");
      out.write("<!-- top ë²í¼ -->\r\n");
      out.write("\t<!-- Scroll to Top Button-->\r\n");
      out.write("\t<a class=\"scroll-to-top rounded\" href=\"#page-top\"> \r\n");
      out.write("\t<i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/sb-admin-2.min.js\"></script>");
      out.write("\r\n");
      out.write("\t<!--========================================================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
