/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-28 12:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.emp.maintenance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import maintenance.model.vo.ImposeViewAptuser;
import java.util.ArrayList;

public final class imposeViewAptuserSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/emp/maintenance/../../common/topbutton.html", Long.valueOf(1571652039501L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("maintenance.model.vo.ImposeViewAptuser");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<ImposeViewAptuser> alist = (ArrayList<ImposeViewAptuser>) request.getAttribute("alist");
	int currentPage = (Integer) request.getAttribute("currentPage");
	int beginPage = (Integer) request.getAttribute("beginPage");
	int endPage = (Integer) request.getAttribute("endPage");
	int maxPage = (Integer) request.getAttribute("maxPage");
	String userId = (String) request.getAttribute("userId");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- head 시작 -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>HIAPTProject</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"/hiapt/resources/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"/hiapt/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/hiapt/resources/css/basic.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/hiapt/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--// css or jQuery or javaScript 삽입 부분    -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 왼쪽 메인 메뉴바 시작 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 왼쪽 메인 메뉴바 끝  -->\r\n");
      out.write("\t\t<!-- ================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--- 중앙 전체 큰 틀 ---------------------------------------------->\r\n");
      out.write("\t\t<!-- Content Wrapper -->\r\n");
      out.write("\t\t<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\t\t\t<!-- Main Content -->\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ================================================================================= -->\r\n");
      out.write("\t\t\t\t<!---탑메뉴  시작 =================---------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!---탑 메뉴 끝 ------------------------------------------->\r\n");
      out.write("\t\t\t\t<!--========================================================================================== -->\r\n");
      out.write("\t\t\t\t<!-- Begin Page Content -->\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<!-- 본문 타이틀 들어가는 부분 ---->\r\n");
      out.write("\t\t\t\t\t<h1 class=\"h3 mb-4 text-gray-800\">세대주 정보</h1>\r\n");
      out.write("\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t전체 목록 :");
      out.print(alist.size());
      out.write("개\r\n");
      out.write("\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t<!--///////본문 내용 시작 ///////-------->\r\n");
      out.write("\t\t\t\t\t<div class=\"card shadow mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Close\" onclick=\"window.close()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 동/호 검색 -->\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"/hiapt/imvas\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"search\" value=\"userid\" /> <label>동/호&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>&nbsp; <input type=\"submit\" value=\"검색\" onclick=\"sendIt()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<form name=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">동/호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">적용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (int i = 0; i < alist.size(); i++) {
												ImposeViewAptuser a = alist.get(i);
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><p id=\"parentId1\">");
      out.print(a.getUserId());
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><p id=\"parentId2\">");
      out.print(a.getUserName());
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(a.getUserPhone());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" value=\"전달하기\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"sendChildValue()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link popover-test checkBtn\">적용</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t/* function sendChildValue(){\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.opener.document.getElementById(\"parentId1\").value = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.opener.document.getElementById(\"parentId2\").value = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.self.close();\r\n");
      out.write("\t\t\t\t\t\t\t}\t */\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".checkBtn\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdArr = new Array(); // 배열선언\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar checkBtn = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 현재 클릭된 row(<tr>)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tr = checkBtn.parent().parent();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td = tr.children();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"클릭한 row의 모든 데이터 : \" + tr.text());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar userid = td.eq(0).text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar username = td.eq(1).text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"클릭한 row의 1번 데이터 : \" + userid);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"클릭한 row의 2번 데이터 : \" + username);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 반복문을 통해서 배열에 값을 담아 사용할 수 잇다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttd.each(function(i){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdArr.push(td.eq(i).text());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"배열에 담긴 값 : \" + tdArr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twindow.opener.document.getElementById(\"parentId1\").value = userid;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twindow.opener.document.getElementById(\"parentId2\").value = username;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twindow.self.close();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- pageing -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"paging_simple_numbers\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (userId != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((beginPage - 10) < 1) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((beginPage - 10) <= 9) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (int p = beginPage; p <= endPage; p++) {
														if (p == currentPage) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
													}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((endPage + 10) > maxPage) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item previous\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((beginPage - 10) < 1) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item previous back\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active back\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(beginPage - 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&lsaquo;&lsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((beginPage - 10) <= 9) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dataTable_previous\"><a href=\"/hiapt/imvas?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"0\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (int p = beginPage; p <= endPage; p++) {
														if (p == currentPage) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item active next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(p);
      out.write("\" aria-controls=\"dataTable\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-dt-idx=\"");
      out.print(p);
      out.write("\" tabindex=\"0\" class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
													}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if ((endPage + 10) > maxPage) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											} else {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(endPage + 10);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"paginate_button page-item next\" id=\"dataTable_next\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/hiapt/imvas?page=");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-controls=\"dataTable\" data-dt-idx=\"");
      out.print(maxPage);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"0\" class=\"page-link\">&rsaquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"window.close()\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End of Main Content -->\r\n");
      out.write("\t\t\t<!---//// 본문 내용 끝 ///////------------------->\r\n");
      out.write("\t\t\t<!-- footer 시작 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- footer 시작 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End of Content Wrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End of Page Wrapper -->\r\n");
      out.write("\t<!--========================================================================================== -->\r\n");
      out.write("\t<!-- top 버튼 -->\r\n");
      out.write("\t");
      out.write("<!-- top ë²í¼ -->\r\n");
      out.write("\t<!-- Scroll to Top Button-->\r\n");
      out.write("\t<a class=\"scroll-to-top rounded\" href=\"#page-top\"> \r\n");
      out.write("\t<i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("<!--========================================================================================== -->\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/hiapt/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"/hiapt/resources/js/sb-admin-2.min.js\"></script>");
      out.write("\r\n");
      out.write("\t<!--========================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
